OCR-D/core

ocrd/characterize/characterizing.py, ocrd/init/initializing.py, ocrd/scripts/run.py
Seems as simple as replacing the import statement (at this early state of dev).
=> change xml.etree to lxml.etree

ocrd/scripts/run.py, ocrd/segment/__init__.py, ocrd/segment/segmenting.py, requirements.txt
fixes #26 
fixes #25 
By now, line coordinates are estimated with respect to the surrounding text region. Not sure yet if this is PAGE-compliant. Tested with the sample images from https://github.com/OCR-D/spec. CLI works, e.g.,
```bash
$ run-ocrd ../spec/io/example/mets.xml
```
Would be great to hear your thoughts on that.
=> * first version of segmentation of regions into lines

ocrd/constants.py, ocrd/model/ocrd_mets.py, test/model/test_ocrd_mets.py
Add a `unique_identifier` property to mets to get the mods:identifier according to spec.
=> METS unique_identifier

ocrd/model/ocrd_exif.py, ocrd/utils.py, test/test_utils.py
PNG has a different metadata mechanism than TIFF. I was of the impression that common keys get normalized but apparently they do not. I.e. we must differentiate between `EXIF:ImageWidth` and `PNG:ImageWidth`.
Still has some debugging statements that need to go before merge.
=> EXIF handling of PNG metadata

ocrd/decorators.py, ocrd/model/ocrd_mets.py, ocrd/model/ocrd_page.py, ocrd/model/yaml/ocrd_tool.schema.yml, ocrd/processor/base.py, ocrd/validator.py, ocrd/workspace.py, test/test_resolver.py, test/test_validator.py, test/validation/test_parameter_validator.py
* Enforce processor subclasses to pass ocrd_tool.json to constructor
* Validate parameters for the tools and fill in defaults so they are available at process time in `self.parameter`
* Some py2/py3 compat fixes
=> Parameter validation defaults

ocrd/cli/workspace.py
e.g.
```sh
$ ocrd workspace -d /path/to find
http://server/foo.tiff
$ ocrd workspace -d /path/to find --output-field local_filename
/path/to/foo.tiff
$ ocrd workspace -d /path/to find --output-field ID
FOO_0001
```
To get a list of possible fields: `ocrd workspace find --help`
=> cli: workspace find with configurable output field, #99

ocrd/resolver.py, ocrd/validator.py, ocrd/workspace.py, test/test_validator.py
…if none other was specified.
This will use the "original" mets file for output files/file groups and write files to the directory of the original files.
Less clean but more intuitive.
Needs testing to make sure we're not clobbering files.
=> :fire: Use the directory of an existing mets.xml file as the working dir

CHANGELOG.md, ocrd/model/mets-empty.xml, ocrd/model/ocrd_mets.py, ocrd/resolver.py, test/model/test_ocrd_mets.py
When running
```sh
ocrd workspace init
```
this is the output now:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:                  
schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-0.xsd http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-6.
xsd http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version17/mets.v1-7.xsd http://www.loc.gov/mix/v10 http://www.loc.gov/standards/mix/mix10/mix10.xsd">
<mets:metsHdr CREATEDATE="2018-09-20 14:14:30.849365">
<mets:agent TYPE="OTHER" OTHERTYPE="SOFTWARE" ROLE="CREATOR">
<mets:name>ocrd/core v0.8.3</mets:name>
</mets:agent> …
```
=> mets: record creation date and core version on creating METS, fix #147

.pylintrc, ocrd/constants.py, ocrd/model/__init__.py, ocrd/model/ocrd_agent.py, ocrd/model/ocrd_mets.py, ocrd/model/ocrd_page.py, ocrd/processor/base.py, ocrd/resolver.py, ocrd/workspace.py, setup.py, test/model/test_agent.py, test/model/test_ocrd_mets.py, test/processor/test_processor.py
=> Add agent for processors on save

ocrd/cli/process.py, ocrd/decorators.py, ocrd/processor/base.py
- renamed argument for METS file inherited from general CLI
- iterate through tool json tools dict (not list), taking 'executable' (not 'binary')
- enforce tool json as path name, add help
=> fix CLI `ocrd process`

ocrd/decorators.py
Small refactoring that allows commands like `bag`, `spill`, `backup ...` etc. to use just the `--log-level` option.
=> factor decorator for log-level CLI out of ocrd_cli_options

CHANGELOG.md, Makefile, ocrd/__init__.py, ocrd/cli/__init__.py, ocrd/cli/process.py, ocrd/cli/workspace.py, ocrd/constants.py, ocrd/processor/base.py, ocrd/workspace.py, ocrd/workspace_backup.py, requirements.txt, setup.py
Here's an implementation of OCR-D/spec#90.
* mets.xml is backed up to a dir '.backup/${sha256 of mets.xml}.${timestamp}'
* <del>backups automatically created on workspace.save_mets unless overridden (`--no-backup` to `ocrd workspace`)</del> backups can be enabled with `--backup` to `ocrd workspace`)
* `ocrd workspace backup list` lists something like:
```
a13cef8 - 2018-11-01 19:51:22 -    32850 B ['OCR-D-IMG', 'OCR-D-IMG-BIN-KRAKEN', 'OCR-D-SEG-LINE', 'FOOBAR']
ab4005d - 2018-11-01 19:51:18 -    32705 B ['OCR-D-IMG', 'OCR-D-IMG-BIN-KRAKEN', 'OCR-D-SEG-LINE', 'FOOBAR']
54609c9 - 2018-11-01 19:50:37 -    32409 B ['OCR-D-IMG', 'OCR-D-IMG-BIN-KRAKEN', 'OCR-D-SEG-LINE', 'FOOBAR']
039ac05 - 2018-11-01 19:50:25 -    32249 B ['OCR-D-IMG', 'OCR-D-IMG-BIN-KRAKEN', 'OCR-D-SEG-LINE']
16dca62 - …
```
=> [WIP] workspace backup

test/model/test_ocrd_mets.py
...and thereby saying Happy New Year!
=> check METS identifier date against current year (instead of 2018)

CHANGELOG.md, ocrd_models/ocrd_models/ocrd_exif.py, tests/model/test_exif.py
OCR-D#256, OCR-D#37, OCR-D/ocrd_tesserocr#54
=> Improve pixel density logic in OcrdExif

ocrd/bashlib/src/parse_argv.bash, ocrd/ocrd/cli/bashlib.py, ocrd/ocrd/lib.bash, ocrd_models/ocrd_models/constants.py
- quote all FS path parameters to prevent tokenization
- convert mets_file and working_dir to absolute paths
(to ensure this still works after chdir; fixes #283)
- do not just set defaults, also validate values:
- mets_file must be readable, otherwise fail
- working_dir must be directory, otherwise fail
- log_level must conform to spec, otherwise fail
- input_file_grp must conform to spec, otherwise warn
- output_file_grp must conform to spec, otherwise warn
=> improve bashlib ocrd__parse_argv:

CHANGELOG.md, ocrd/ocrd/workspace.py, ocrd/ocrd/workspace_backup.py, ocrd/requirements.txt
Just a quick idea on how to do this. Should investigate where else mets.xml is opened for writing.
@bertsky
=> [WIP] atomic write of mets.xml, fix #278

README.md, ocrd/ocrd/__init__.py, ocrd_models/ocrd_models/__init__.py, ocrd_utils/ocrd_utils/__init__.py
- re-instate item for coordinate conversion utils (not first any longer)
- improve RST indentation
=> fix __init__ docstring order/markup

ocrd/ocrd/workspace.py
Fixes a bug in which `image_from_page`: 
- returned a xywh dictionary without the 'angle' key and without rotating the image if no `AlternativeImage` was present already and if `Border` or `PrintSpace` where supplied,
- returned a xywh dictionary with the 'angle' key and without rotating the image if no `AlternativeImage` was present already and if no `Border` or `PrintSpace` where supplied
(This became relevant if page-level deskewing had been run earlier without producing `AlternativeImage`.)
=> image_from_page: ensure to rotate image if orientation

ocrd_validators/ocrd_validators/workspace_validator.py, tests/validator/test_workspace_validator.py
@bertsky Is that a reasonable way to use `workspace.image_from_page` (to get the OcrdExif metadata)?
=> validate PAGE and image exif height/width match, fix #229

CHANGELOG.md, ocrd/ocrd/cli/process.py, ocrd/ocrd/decorators.py, tests/test_decorators.py
When running processors (core CLI or other), it should **not** be required to give `-m mets.xml` but default instead.
=> process: replace -m/--mets requirement by default

CHANGELOG.md, ocrd/ocrd/decorators.py, ocrd/ocrd/processor/base.py, ocrd_validators/ocrd_validators/json_validator.py, tests/base.py, tests/processor/test_processor.py, tests/test_decorators.py
These are now equivalent:
```sh
$ cat params.json
{"foo": 42}
$ ocrd-foo -p params.json
$ ocrd-foo -p '{"foo": 42}'
$ ocrd-foo -p <(echo '{"foo": 42}')
$ ocrd-foo -p '$(cat params.json)"
```
The second one is the new variant.
@mikegerber @bertsky
=> allow parameter CLI arg to contain JSON strings, fix #239

.pylintrc, CHANGELOG.md, ocrd/ocrd/cli/workspace.py, ocrd/ocrd/decorators.py, ocrd/ocrd/processor/base.py, ocrd/ocrd/resolver.py, ocrd/ocrd/workspace.py, ocrd/ocrd/workspace_bagger.py, ocrd_modelfactory/ocrd_modelfactory/__init__.py, ocrd_models/ocrd_models/ocrd_file.py, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/constants.py, ocrd_utils/ocrd_utils/logging.py, ocrd_validators/ocrd_validators/workspace_validator.py, requirements_test.txt, tests/base.py, tests/cli/test_workspace.py, tests/model/test_ocrd_file.py, tests/model/test_ocrd_mets.py, tests/test_decorators.py, tests/test_logging.py, tests/test_model_factory.py, tests/test_resolver.py, tests/test_utils.py, tests/test_workspace.py, tests/validator/test_ocrd_zip_validator.py, tests/validator/test_page_validator.py, tests/validator/test_workspace_validator.py
I went through the code and tried to get rid of all the logic that was based on `file://` URLs and the complexities from supporting all sorts of URLs.
In particular, filenames will be resolved to relative paths from the workspace directory whereever possible. To achieve that, employ the `pushd_popd` context manager in all places where relative filenames can be expected.
Split workspace tests from resolver tests.
`Workspace.download_to_directory`'s  boolean `overwrite` argument replaced with an `if_exists` string, that can handle existing files as an exception (`"raise"`), skip them (`"skip"`, the default) or overwrite them (`"overwrite"`).
Fix #302 
Fix #272
Fix #248 
Fix #227
Fix #96 
Supersedes #266
=> Escape from file hell

CHANGELOG.md, ocrd/ocrd/cli/ocrd_tool.py
Reuse the parameter parsing logic also used in the processor base class.
=> ocrd-tool parse-params: accept literal JSON

ocrd/ocrd/cli/zip.py
=> spill: use dest instead directory as parameter name

ocrd_models/ocrd_models/ocrd_file.py, ocrd_validators/ocrd_validators/workspace_validator.py, tests/cli/test_workspace.py, tests/model/test_ocrd_file.py, tests/test_workspace.py
This will allow setting @LOCTYPE and @OTHERLOCTYPE.
Default for @LOCTYPE is `OTHER` and implies `@OTHERLOCTYPE = "file"` for now.
Setting @LOCTYPE to something different from `OTHER` will unset `@OTHERLOCTYPE`.
=> set LOCTYPE and OTHERLOCTYPE as necessary, fix #310

CHANGELOG.md, ocrd_utils/requirements.txt, tests/test_utils.py
I cannot reproduce the segfaults in 6.2.0 that were plaguing 6.0.0 and 6.1.0.
Tested by running `test_pil_version` a few thousand times, which consistently fails in >= 6.0.0 < 6.2.0 but not in 6.2.0
Can someone confirm this please?
It's also highly advisable to update because of https://nvd.nist.gov/vuln/detail/CVE-2019-16865
=> Update Pillow to 6.2.0

CHANGELOG.md, ocrd/ocrd/workspace.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/setup.py
Workspace.image_from_*: when rotation is necessary, do not always fill with white; instead, determine the background color by median, and only use white for binary images; moreover, add a transparency 
channel if the input mode allows it
=> improve handling of rotation

ocrd_validators/ocrd_validators/workspace_validator.py, tests/validator/test_workspace_validator.py
OCR-D/spec#129
OCR-D/assets#33
=> reduce pixel_density problem severity: error -> warning,

Makefile
perhaps also (for modules still using the old spec) `python3-virtualenv`?
=> add python3-venv dependency to deps-ubuntu

ocrd/ocrd/decorators.py, tests/test_decorators.py
When passing `--version` to a processor inheriting from `Processor`, ignore exceptions thrown in the constructor
=> decorator: --version should ignore validation errors, fix #349

CHANGELOG.md, ocrd/ocrd/task_sequence.py, ocrd_validators/ocrd_validators/parameter_validator.py, tests/processor/test_processor.py, tests/test_task_sequence.py, tests/validator/test_ocrd_tool_validator.py, tests/validator/test_parameter_validator.py
=> Improve param validation

Makefile, tests/model/test_ocrd_mets.py
wheel is required for builds.
pip is already available, but typically too old.
pip 19.0 or newer is required for manylinux2010 platform tag support.
pip 19.3 or newer is required for manylinux2014 platform tag support.
Installation of tensorflow==2.0.0 for example requires manylinux2010.
=> Install latest Python packages pip, wheel

ocrd/ocrd/workspace.py
Fixes #367
Please test if this is sufficient on real workflows!
=> image_from_*: increase tolerance for size mismatch after rotation to 2px

ocrd/ocrd/cli/workspace.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/deprecate.py, ocrd_utils/ocrd_utils/logging.py, ocrd_validators/ocrd_validators/page_validator.py, ocrd_validators/ocrd_validators/workspace_validator.py, ocrd_validators/requirements.txt, tests/model/test_exif.py, tests/validator/test_page_validator.py, tests/validator/test_workspace_validator.py
- improve recursive validation of multi-level textequiv consistency:
* regions (e.g. Table) may contain regions (e.g. Text)
* 'fix' recursively by going bottom-up
* better reports, more logging
* simplify
- add recursive validation of multi-level coordinate consistency:
* add all region types, also consider Baseline
* introduce 2 more error cases into ValidationReport:
- CoordinateValidityException (self-intersecting, non-contiguous,
too short or negative path)
- CoordinateConsistencyException (child extends beyond parent)
* introduce 2 new parameters:
- check_coords (valid paths and consistent child/parent relations
within the normal hierarchy)
- check_baseline (the same only for TextLine.Coords vs Baseline)
* expose them as 1 new CLI parameter `--page-discipline` (analoguous to …
=> PAGE validator: coordinate self-validity and mutual consistency

ocrd_models/ocrd_models/ocrd_exif.py, tests/model/test_exif.py
The fix is trivial, the complex thing was getting the test metadata right.
=> PNG with DPI have no tag, fix #395

ocrd/ocrd/resolver.py, tests/cli/test_workspace.py, tests/test_workspace.py
This should fix #319.
Note that this simply concatenates `Path.cwd()` and `mets_url` if the latter is a relative filename. It does not do `Path.resolve` since that would resolve symlinks, i.e. if `mets.xml` was pointing somewhere else, this might break the contract on all files being relative to the `mets.xml`. I'm happy to change this if you think this is too cautious.
=> resolver: if mets_url is relative path, resolve before anything else

ocrd/ocrd/workspace.py, tests/test_workspace.py
* When creating files with `workspace.add_file`, single-component file paths (i.e. just the basename of a file) were treated as directories
* When downloading files to a workspace, check first whether those files to be added already exist on disk and are within the workspace directory.
=> Fix workspace.download file

ocrd/ocrd/decorators.py, ocrd/ocrd/processor/base.py, ocrd/ocrd/task_sequence.py, ocrd_validators/ocrd_validators/workspace_validator.py, tests/test_decorators.py, tests/test_task_sequence.py, tests/validator/test_workspace_validator.py
Adds a static method `check_file_grp` to WorkspaceValidator which is called before run_processor when wrapping processors and will fail if
- input file groups are NOT in mets
- output file groups ARE in mets
=> Validate input group

ocrd/bashlib/src/usage.bash, ocrd/ocrd/cli/ocrd_tool.py, ocrd/ocrd/decorators.py, ocrd/ocrd/lib.bash, ocrd/ocrd/processor/__init__.py, ocrd/ocrd/processor/base.py
Before:
```
$ ocrd-tesserocr-recognize -h
Usage: ocrd-tesserocr-recognize [OPTIONS]
Try "ocrd-tesserocr-recognize --help" for help.
Error: no such option: -h
$ ocrd-tesserocr-recognize --help
Usage: ocrd-tesserocr-recognize [OPTIONS]
Options:
-V, --version                   Show version
-l, --log-level [OFF|ERROR|WARN|INFO|DEBUG|TRACE]
Log level
-J, --dump-json                 Dump tool description as JSON and exit
-p, --parameter TEXT            Parameters, either JSON string or path to
JSON file
-g, --page-id TEXT              ID(s) of the pages to process
-O, --output-file-grp TEXT      File group(s) used as output.
-I, --input-file-grp TEXT       File group(s) used as input.
-w, --working-dir TEXT          Working Directory
-m, --mets TEXT                 METS to process
--help …
```
=> customized --help for processors

ocrd/bashlib/src/parse_argv.bash, ocrd/ocrd/lib.bash, ocrd_utils/ocrd_utils/__init__.py, tests/test_utils.py
Currently
```python
self.assertEqual(parse_json_string_or_file(), {})  # true
self.assertEqual(parse_json_string_or_file(''), {}) # error
```
This makes empty strings equivalent to `None` which is already equivalent to an empty object. Which makes sense in this context I think.
Also fixes the bashlib to default `${ocrd__argv[parameter]}` to be `"{}"` as [proposed by @bertsky](https://github.com/OCR-D/core/issues/381)
=> Parse empty string  as json object

ocrd/bashlib/src/parse_argv.bash
I did not see it myself in the review for #400, the bash code looked unsuspicious. But it appears bash is sensitive to closing braces when doing parameter expansion.
Without the fix you will get errors like this from current master:
```bash
ocrd-im6convert -I ORIGINAL -O OCR-D-IMG-PNG -p OCR-D-IMG-PNG.json
File "decorators.py", line 30, in <lambda>
callback=lambda ctx, param, value: parse_json_string_or_file(value))
File "ocrd_utils/__init__.py", line 808, in parse_json_string_or_file
raise err       # pylint: disable=raising-bad-type
ValueError: Error parsing 'OCR-D-IMG-PNG.json}': Expecting value: line 1 column 1 (char 0)
Makefile:301: recipe for target 'OCR-D-IMG-PNG' failed
```
Maybe we should have some pseudo-processor test in `ocrd/bashlib/test` (beside the arg-parsing test).
=> bashlib: escape } in default (regression from 2d89c22ae3)

CHANGELOG.md, ocrd/ocrd/cli/workspace.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, tests/cli/test_workspace.py, tests/model/test_ocrd_mets.py, tests/test_workspace.py
This changes the semantics of the kwargs/CLI params:
* `--keep-file`: Whether to keep local file on disk. Defaults to `false`, so files on disk are deleted by default
* `--force`: Do not abort if the file is not found in METS or on disk
* `--recursive`: also delete containing files. Required for non-empty group
* `--keep-files`: Passed as `--keep-file` to `remove`
* `--force`: Continue removing even if group or containing mets:files not found in METS or any files not found on HDD
```sh
ocrd workspace remove-group -rf DEFAULT
ocrd workspace remove -f page1_img
ocrd wworkspace remove -f -k page1_img
```
This is not yet finished but I'd appreciate feedback whether this is the right direction, esp. @bertsky @mikegerber E.g. do you want a `--recursive` option (as it is now) or a …
=> improve workspace.remove_file/remove_group, #245

.coveragerc, ocrd/ocrd/cli/__init__.py, ocrd/ocrd/cli/validate.py, ocrd/ocrd/task_sequence.py, tests/cli/test_validate.py, tests/validator/test_page_validator.py
Yet untested, soliciting feedback on the interface before working further on this.
=> "ocrd validate" cli, #353

ocrd_validators/ocrd_validators/page_validator.py
By request of @tboenig, this slightly improves useability of the coordinate checks.
Example output (scroll right to see the change):
```
<error>INVALIDITY in Word ID 'w46' of 'weigel_gnothi02_1618/page/weigel_gnothi02_1618_0003.xml': coords '1270,526 1270,527 1271,527 1271,529 1272,529 1272,531 1273,531 1273,544 1283,544 1283,545 1284,545 1283,545 1283,560 1282,560 1282,561 1281,561 1281,562 1280,562 1280,563 1279,563 1279,564 1265,564 1265,565 1221,565 1221,566 1196,566 1196,541 1197,541 1197,540 1239,540 1239,532 1240,532 1240,530 1241,530 1241,529 1242,529 1242,527 1256,527 1257,526' - Self-intersection[1283 545]</error>
```
=> Improve coordinate validator

ocrd_validators/ocrd_validators/workspace_validator.py, tests/validator/test_workspace_validator.py
Debugging #324 I understand now that the `TEMP/*` files are being created for the AlternativeImages in PAGE. Even if the PAGE is available locally, the images might not be. Even without `--download`, these images were loaded.
Instead of further complicating the logic for image resolving, this PR requires `--download` for the `_validate_dimensions` check. This is too strict for PAGE files with only local image references or w/o any image references.
=> workspace validation: clarify why _validate_dimension requires --download

ocrd/ocrd/resolver.py, tests/test_resolver.py
This changes the behavior: if `clobber_mets` is `False` and METS is to be downloaded but already exists in the destination: **skip downloading** instead of **rasing an exception**.
Translating between `clobber_mets` and `if_exists` is not a good solution. The former should be replaced with the latter.
=> Clobber mets download to directory

ocrd/ocrd/processor/base.py
e.g. for ocrd-olena-binarize:
```
Parameters:
"impl" [string - REQUIRED] The name of the actual binarization
algorithm
"win-size" [number - 101] Window size
"k" [number - 0.34] Sauvola's formulae parameter
```
becomes
```
Parameters:
"impl" [string - REQUIRED] The name of the actual binarization
algorithm Possible values: ["otsu", "singh", "niblack", "wolf",
"kim", "sauvola-ms-split", "sauvola-ms-fg", "sauvola-ms",
"sauvola"]
"win-size" [number - 101] Window size
"k" [number - 0.34] Sauvola's formulae parameter
```
=> --help: show 'enum' values for parameters that define them, fix #426

ocrd/ocrd/cli/validate.py, ocrd_validators/ocrd_validators/page_validator.py, tests/validator/test_page_validator.py
Fixes #430.
Note: renaming `index1` to `first` in the CLI option for the `validate` command is backwards incompatible. But it's only the CLI (not the API), and was just introduced recently, and there were no other choices anyway, so I doubt this is significant.
=> PAGE validator TextEquiv consistency: first instead of index1

ocrd/ocrd/workspace.py, ocrd_utils/ocrd_utils/constants.py, tests/test_utils.py, tests/test_workspace.py
Fixes #439
Maps from the [most common PIL/Pillow supported image formats](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html) to media types.
Changes the signature of `workspace.save_image_file`, replacing the `format` parameter with a `mimetype` parameter.
=> Map between PIL and media type

ocrd_utils/ocrd_utils/__init__.py, tests/test_utils.py
Run into this in a real world example on my Linux Ubuntu:
```bash
[...]
File "/home/j23d/projects/ocrd/ocrd_all/.venv/lib/python3.6/site-packages/click/core.py", line 96, in invoke_param_callback
return callback(ctx, param, value)
File "/home/j23d/projects/ocrd/ocrd_all/core/ocrd/ocrd/decorators.py", line 30, in <lambda>
callback=lambda ctx, param, value: parse_json_string_or_file(value))
File "/home/j23d/projects/ocrd/ocrd_all/core/ocrd_utils/ocrd_utils/__init__.py", line 799, in parse_json_string_or_file
with open(value, 'r') as f:
OSError: [Errno 36] File name too long: '{"dpi": -1, "textequiv_level": "word", "overwrite_words": false, "raw_lines": false, "char_whitelist": "", "char_blacklist": "", "char_unblacklist": ""}'
```
=> Parsing a json string should also work with long json strings.

.gitignore, CHANGELOG.md, Dockerfile, Makefile, ocrd/ocrd/processor/base.py, ocrd_utils/README.md, ocrd_utils/ocrd_logging.conf, ocrd_utils/ocrd_utils/constants.py, ocrd_utils/ocrd_utils/logging.py, requirements_test.txt, tests/base.py, tests/processor/test_processor.py, tests/test_decorators.py, tests/test_logging.py, tests/test_resolver.py, tests/test_workspace.py
Enable python log files (see: https://docs.python.org/3.6/howto/logging.html#configuring-logging)
Advance: Configuration logic and behavior is separated from programming flow
Example Configuration: 
[ocrd_logging.zip](https://github.com/OCR-D/core/files/4455950/ocrd_logging.zip)
The example Configuration affects out-of-the the following ocr-modules:
* ocrd_utils
* ocrd.workspace
* processor.RepairSegmentation
* processor.OcropySegment
* processor.OcropyDewarp
* processor.TesserocrRecognize
The following ocrd-modules are not affected (due they are not pythonic or of other reasons)
* ocrd-im6convert
* ocrd-olena-binarize
* OCR-D-SEG-PAGE-anyocr
=> [app][feat] use config file for logging

Makefile, ocrd_models/ocrd_models/ocrd_page_generateds.py, ocrd_models/ocrd_page_user_methods.py, requirements_test.txt, tests/model/test_ocrd_page.py
... so instances of generateDS-generated class can be used as keys in dict etc.
=> PAGE API: add __hash__ to generated code

Makefile, ocrd_models/ocrd_models/ocrd_page.py, ocrd_models/ocrd_models/ocrd_page_generateds.py, tests/model/test_ocrd_page.py
...by any means necessary
After exhausting all documented approaches to make the output of `OcrdPage.to_xml` use the `pc:` namespace prefix consistently, I resorted to another `sed` hack that seems to do the trick.
I will try to clear this up with upstream generateDS but for the time being this should at least support the use case https://github.com/OCR-D/core/issues/269#issuecomment-621338143 .
=> 💩 ocrd_page: export with pc: namespace

.pylintrc, ocrd/ocrd/cli/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/constants.py, ocrd_validators/ocrd_validators/bagit-profile.yml, tests/model/test_ocrd_file.py, tests/model/test_ocrd_mets.py
<del>Still WIP, need to ensure that this won't break anything. In particular the `local_filename` handling of OcrdFile. Ideally we can remove that too and can be certain that all information is serializable.
Two important changes:
* files are no longer trivially cached in a dict in OcrdMets. This was useful in development but is a recipe for Out-of-memory errors for real-world data
* `OcrdMets.find_files` has been changed from two-step process with search implemented using Xpath filters and instantiation of OcrdFiles by file ID to a single-step process that iterates over **all** the files in METS and filters. In all cases I have tested, this "filtering" approach is equal or faster in speed. It's less noticeable with few files but with very large METS file, the improvement in speed is …
=> drop OcrdFile caching in OcrdMets, one-go regex search, fix #446

ocrd/ocrd/processor/base.py, tests/test_logging.py
This changes the formatting of messages shown in the profiling logger such that the parameter string can directly be re-used on the command line.
=> processor.base: format profile log message params in JSON

ocrd/ocrd/workspace.py
=> ocrd.workspace: ignore PrintSpace (don't interpret as Border anymore)

CHANGELOG.md, ocrd_models/ocrd_models/ocrd_file.py, tests/test_model_factory.py
Removes unused argument `instance` and adds `ID` as a constructor argument.
Required by upcoming PR, so will merge if tests pass.
=> Ocrdfile cleanup

ocrd/ocrd/cli/workspace.py, tests/cli/test_workspace.py
The problem was that `os.path.join` has a peculiar behavior when trying to concatenate absolute paths: It will just return the last one. Therefore the `exists` check only checked whether the source file exists - which it does, obviously - and never copied them to the workspace.
I added a test to reproduce #519 so this won't happen in the future.
=> workspace add: os.path.join behavior led to faulty existence check

ocrd_models/ocrd_models/ocrd_file.py, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/constants.py, tests/model/test_ocrd_file.py
Implement `__eq__`, so different instances of equivalent OcrdFile can be compared with `==` and `!=`.
=> Ocrd file eq

ocrd/ocrd/cli/workspace.py
In partial fulfillment of the solutions discussed for #517: 
- still under the old interface (only `--directory` and `--mets-basename`, no `--mets`)
- make self-consistent (as a first step)
- don't break remote URL argument for `validate` (which should naturally be dropped in favour of `--mets`) yet, but make optional (using local METS instead of `'./mets.xml'` by default)
- don't break explicit directory argument for `clone` and for `init` (which should naturally be dropped in favour of `--directory`) yet, but make optional (using `--directory` setting instead of `'.'` by default)
=> workspace CLI: respect --directory / --mets-basename

ocrd_validators/ocrd_validators/constants.py, ocrd_validators/ocrd_validators/workspace_validator.py, requirements_test.txt, tests/validator/test_workspace_validator.py
* Let's stop complaining about fileGrp `@USE` not fitting our naming convention. Outside of GT, it's just pointless.
* `wheel` is required to build `bdist_wheel` for core
=> validation of file groups downgraded to notice, allow PRE fileGrp/USE prefix

ocrd/MANIFEST.in, ocrd/setup.py
It's more reliable than `package_data` to catch all data files we want to ship with the package dist.
=> replace package_data with MANIFEST.in

ocrd/ocrd/processor/base.py, ocrd_models/ocrd_models/ocrd_mets.py, tests/cli/test_validate.py, tests/model/test_exif.py, tests/processor/test_processor.py, tests/test_task_sequence.py
Implements the logic [proposed by @bertsky](https://github.com/cisocrgroup/ocrd_cis/pull/57#issuecomment-656336593).
=> Adapt Processor.input_files to handle PAGE-XML and images in same group

CHANGELOG.md, ocrd_utils/ocrd_utils/str.py, tests/test_utils.py
To allow more expressive error messages in case input/output group cardinality is not what is expected.
=> assert_file_grp_cardinality: allow optional "msg" keyword param

ocrd/ocrd/workspace.py
This can be considered a follow-up to #390. We missed that instance of `PIL.Image.open` usage without closing the FD. Since in this function we must return the `Image` object, we cannot use a context manager, but have to just give up the FD itself. See [here](https://pillow.readthedocs.io/en/stable/reference/open_files.html#file-handling)
=> workspace: ensure PIL.Image.open FD gets closed

ocrd/ocrd/processor/helpers.py, ocrd/ocrd/task_sequence.py
If a task in `ocrd process` fails, STDOUT/STDERR are printed as bytes, when they should be decoded to a string.
=> ocrd process: stdout/stderr as strings, not bytes

ocrd/ocrd/cli/log.py, ocrd/ocrd/cli/process.py, ocrd/ocrd/cli/validate.py, ocrd/ocrd/cli/workspace.py, ocrd/ocrd/cli/zip.py, ocrd/ocrd/decorators.py, ocrd_utils/ocrd_utils/logging.py, tests/test_decorators.py
Fix #589 (instead of #591)
This seems to work. Not so sure about the placement of `initLogging()` at the module level of `ocrd.cli.*` though...
=> avoid module-level initLogging for non-interactive CLI commands

ocrd_validators/ocrd_validators/page_validator.py
This fixes a crash in case `ReadingOrder` is empty (which is not allowed in PAGE, but does happen on the input side).
=> ocrd_validators.page_validator: cope with empty RO

ocrd_utils/ocrd_utils/image.py, tests/utils/test_image.py
as a workaround for python-pillow/Pillow#4925
=> ocrd_utils.image: fix bg tuple vs scalar (depending on mode)

ocrd/ocrd/decorators/__init__.py, ocrd/ocrd/decorators/loglevel_option.py, ocrd/ocrd/decorators/ocrd_cli_options.py, ocrd/ocrd/decorators/parameter_option.py, tests/cli/test_log.py
Just a refactoring, `ocrd/decorators.py` was becoming unwieldly.
=> [rfct] split decorators into topical modules

ocrd/ocrd/decorators/__init__.py, tests/base.py, tests/test_decorators.py
<del>This is a surprisingly tricky-to-implement problem: We want processor calls without any arguments to print the help screen and exit with code `1`, i.e. if `sys.argv[2:] == []`.</del>
It really isn't, it was just hard to test because sys.argv contained the arguments to pytest, not to the CLI. Turns out, sys.argv can be overridden at runtime for the tests and checking `not sys.argv[1:]` was enough
<del>
However, I could not find a way to get the un-procesed command line arguments to click. `get_current_context()` does have an `args` property but that only contains the remaining positional arguments after parsing.
If anyone knows a better way to get the click equivalent of `sys.argv[2:]`, I'd be interested!
For now, I've disabled the defaults for `input_file_grp`/`output_file_grp` (as …
=> show help for no-arg processor calls, fix #562, fix #274

ocrd/ocrd/workspace.py, tests/test_task_sequence.py, tests/test_workspace.py
This change forces processors to provide an explicit `pageId` kwarg when using `workspace.add_file`. Non-page-specific data can still be added with `pageId=None`.
=> workspace.add_file: ensure processors consciously pass pageId (or not)

ocrd/bashlib/src/parse_argv.bash, ocrd/ocrd/lib.bash
Makes bashlib behave the same as the Python processor implementations wrt #586, i.e. show help and exit 1 iff no arguments at all.
=> bashlib: align non-arg-help behavior with python core

ocrd_utils/requirements.txt
=> Require numpy<1.19.0 to satisfy requirements of tensorflow

ocrd_utils/ocrd_utils/logging.py
@bertsky This was why I originally had `setOverrideLoglevel` as part of `intiLogging` in #599: When loading from config file and setting the root logger to the override loglevel, all existing loggers must be set to `NOTSET`.
=> logging: set non-root logger to NOTSET also when loading from config file

Makefile
As discussed in https://github.com/OCR-D/ocrd_calamari/issues/46, `calamari-predict` takes [more than 1/3 of the duration](https://github.com/OCR-D/ocrd_calamari/issues/46#issuecomment-710028497) of [the recommended workflow](https://ocr-d.de/en/workflows#best-results-for-selected-pages) on the CPU. Therefore, the `ocrd/all:*-cuda` images should above all support `calamari-predict`, so that it can use GPUs.
Currently, the `ocrd/all:*-cuda` images are based on the `nvidia/cuda:11.0-runtime-ubuntu18.04` image, whereas `calamari-predict` [uses Tensorflow 1.15](https://github.com/OCR-D/ocrd_calamari/blob/master/requirements.txt#L1), which [requires CUDA Toolkit 10.0](https://www.tensorflow.org/install/source#gpu) and the CUDNN7 dynamic library.
This pull request changes the base image to …
=> Use nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04 as the base image

ocrd_utils/ocrd_utils/os.py
The method `os.fchmod` is only available on Unix system.
Therefore developing for `ocrd_utils` or any packages depending on it is not possible on Windows.
As of Python 3.3 `os.chmod` also accepts a file descriptor.
Switching to `os.chmod` has the risk of masking raise conditions that should be prohibited by `AtomicWriterPerms`, but only **on Windows**.
AFAIK running natively on Windows is not a goal of OCR-D (right now).
=> Switch from fchmod to chmod to allow dev on win

ocrd/ocrd/processor/base.py
I think it would be useful to annotate version info directly in the PAGE metadata besides the parameters, example:
```xml
<pc:Labels externalModel="ocrd-tool" externalId="version">
<pc:Label value="0.10.0" type="ocrd-tesserocr-recognize"/>
<pc:Label value="2.19.0" type="ocrd/core"/>
</pc:Labels>
```
I know we have `mets:agent/mets:name` already, but that does not show exactly which file(Grp) came from which version (one can only guess by the order of `mets:agent` entries and the dates of the files.
This is useful especially for GT production where workspaces have a longer digital life, and one sometimes needs to touch and reconstruct previous steps.
=> add_metadata: add version info

ocrd/ocrd/processor/base.py, ocrd/ocrd/workspace.py, tests/processor/test_processor.py
AFAICS this would already be useful for:
- [ocrd-cor-asv-ann-evaluate](https://github.com/ASVLeipzig/cor-asv-ann/blob/master/ocrd_cor_asv_ann/wrapper/evaluate.py) (where I drafted it)
- [ocrd-cis-align](https://github.com/cisocrgroup/ocrd_cis/blob/master/ocrd_cis/align/cli.py) (original implementation)
- [ocrd-dinglehopper](https://github.com/qurator-spk/dinglehopper/blob/master/qurator/dinglehopper/ocrd_cli.py)
- [ocrd-segment-evaluate](https://github.com/OCR-D/ocrd_segment/blob/master/ocrd_segment/evaluate.py)
- [ocrd-segment-from-masks](https://github.com/OCR-D/ocrd_segment/blob/master/ocrd_segment/import_image_segmentation.py)
- [ocrd-segment-replace-page](https://github.com/OCR-D/ocrd_segment/blob/maskrcnn-cli/ocrd_segment/replace_page.py)
Most of these recently broke with the …
=> ocrd.processor.base: add property zip_input_files

ocrd_models/ocrd_models/ocrd_page_generateds.py, ocrd_models/ocrd_page_user_methods.py, ocrd_models/ocrd_page_user_methods/invalidate_AlternativeImage.py, ocrd_models/ocrd_page_user_methods/set_Border.py, ocrd_models/ocrd_page_user_methods/set_Coords.py, ocrd_models/ocrd_page_user_methods/set_orientation.py, ocrd_models/ocrd_page_user_methods/set_points.py
Fixes the issue described in [chat](https://gitter.im/OCR-D/Lobby?at=5f9c00a4dc70b5159adff92a) for all processors based on core Python. (Not sure about bashlib processors...)
(I added a warning to the default `GdsCollector` about the `AlternativeImage` removal. If and when #576 lands, these should appear in OCR-D logging somehow. :crossed_fingers:)
Thus, some workflows will work, while others will need to be re-defined.
As I said above, this still does not expose _all_ bad workflows, as it depends whether processors make their image requirements explicit (`feature_selector` and `feature_filter`) or not. If they do, we'll at least get exceptions `Found no AlternativeImage that satisfies all requirements` when running invalid workflows. But if they don't, there might be strange errors (like …
=> auto-invalidate derived images when changing coords

ocrd/ocrd/processor/base.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py
Here's the latest in our series: "this time I have gotten it right, I'm sure"! 
(Let's just hope we keep failing better.)
The first commit refactors both workspace functions, not only reducing code duplication between page and lower levels, but also helping with the second commit: 
We must __re-crop__ to the new bounding box after rotation! Until now we forgot that. Though we did so consistently between coordinates and images, under some circumstances inconsistency would nevertheless be unavoidable. Plus it helps getting tighter crops from rotated non-rectangular polygons.
The third commit is where things get complicated again: Until now we had a _wrong interpretation_ of what a missing `@orientation` means on the region level. When we extended PAGE with `@orientation` on the page level, …
=> Image API: refactor, re-crop and re-interprete

ocrd_models/ocrd_models/ocrd_page_generateds.py, ocrd_models/ocrd_page_user_methods/prune_ReadingOrder.py
This prevents invalid PAGE-XML from common sloppiness: processors which leave an empty group (e.g. segmentation that did not find regions).
=> prune_ReadingOrder: also check empty groups

ocrd/ocrd/task_sequence.py
I am doing a proof of concept for a workflow server – outside of core, just importing from it – and found this error: the class method should instantiate the passed class, not a fixed one, so subclasses can override properly.
=> TaskSequence.parse: instantiate given class

ocrd_utils/requirements.txt
I have tested this within ocrd_all with sbb_binarization (tf1), anybaseocr (tf21) and the new ocrd_calamari 1.0 (tf24) and have not run into numpy VersionConflicts anymore.
=> ocrd_utils: drop numpy version range, #642

ocrd/ocrd/task_sequence.py
Since run_cli does not (capture and) return stdout and stderr anymore, these references are impossible and unnecessary.
=> task_sequence: remove invalid refs to out/err

ocrd_models/ocrd_models/ocrd_page_generateds.py, ocrd_models/ocrd_page_user_methods.py, ocrd_models/ocrd_page_user_methods/get_AllAlternativeImagePaths.py, ocrd_models/ocrd_page_user_methods/get_AllAlternativeImages.py, tests/model/test_ocrd_page.py
`get_AllAlternativeImage` as an alternative to `get_AllAlternativeImagePaths` that iterates elemens, so is slower but offers access to the underlying AlternativeImages, not just their `@filename`.
=> Get all alternative images

ocrd/ocrd/cli/resmgr.py, ocrd/ocrd/resource_manager.py, ocrd_utils/ocrd_utils/os.py, tests/utils/test_os.py
`ocrd resmgr --location cwd download ...` will now download resource `<res>` to `$PWD/<res>`, not `$PWD/ocrd-resources/<executable>/<res>` as per the spec.
One minor drawback is that `ocrd resmgr list-installed` will no longer pick up resources in `$PWD` because there would be too many false positives, files that are not resources.
=> resmgr: --location cwd means cwd, no subdirs, #663

ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/str.py, tests/model/test_ocrd_mets.py, tests/test_utils.py
When processing works with a non-trivial amount of pages, or when a long process fails in the middle of a run, it would be useful to not only allow comma-separated page ID values but ranges of page IDs.
This PR implements this by introducing the syntax `--page-id <startid>..<endid>` which
* extracts the first contiguous match of numbers of both `<startid>` and `<endid>`
* counts from start to end number and replaces the number in <startid> with the zero-padded current number
E.g. you can do `ocrd-processor -g PHYS_0001..PHYS_0003` is equivalent to `ocrd-processor -g PHYS_0001,PHYS_0002,PHYS_0003` but shorter.
=> implement value range with .. operator for pageId

ocrd/ocrd/cli/resmgr.py, ocrd/ocrd/resource_list.yml, ocrd/ocrd/resource_manager.py
This allows downloading the configs, i.e. parameter sets, used by the upstream tesseract CLI.
=> Resmgr tess config

ocrd_utils/ocrd_logging.conf, tests/base.py, tests/cli/test_bashlib.py, tests/cli/test_log.py, tests/cli/test_workspace.py, tests/model/test_ocrd_page.py, tests/processor/test_processor.py, tests/test_decorators.py, tests/test_logging.py, tests/test_logging_conf.py, tests/test_resolver.py, tests/test_workspace.py, tests/utils/test_os.py, tests/validator/test_json_validator.py, tests/validator/test_ocrd_tool_validator.py, tests/validator/test_ocrd_zip_validator.py, tests/validator/test_page_validator.py, tests/validator/test_workspace_backup.py, tests/validator/test_workspace_bagger.py, tests/validator/test_xsd_validator.py
The unit tests behaved strangely when a `$HOME/ocrd_logging.conf` was present. Most of the errors result from different configuration, hence the `string in processor-output` tests fail, which is to be expected. However, there were issues related to the `os.chdir` call in `setUpClass` in `tests/base.py`. Moving this to `setUp` and ensuring that all tests call `super().setUp` in their own `setUp` (where applicable) fixes this.
Also contains a few improvements to the comments in the bundled `ocrd_logging.conf` by @bertsky.
We should probably create an ocrd_logging.conf that is equivalent to the builtin config and run the unit tests once without `ocrd_logging.conf` and once with.
=> Logging test fix

ocrd_utils/ocrd_logging.conf, ocrd_utils/ocrd_utils/logging.py, tests/test_logging_conf.py
The default logger will log to STDERR. As discussed in #667, this will eliminate the need for workarounds like completely disabling logging to ensure logging output does not interfere with parseable output.
The default configuration file has also been adapted accordingly.
=> log to STDERR not STDOUT, fix #667

ocrd/ocrd/cli/workspace.py
This fixes the following previously undetected bug:
```sh
ocrd workspace merge -g PHYS_0015..PHYS_0812 -G BIN-SBB --copy-files ../other/mets.xml
TypeError: merge() got an unexpected keyword argument 'file_grp'
```
=> workspace.merge: fix file-grp parameter

Makefile, ocrd_models/ocrd_models/ocrd_page_generateds.py
No need to be backwards-compatible with Python 2.x
=> Remove requirement on six

ocrd_utils/ocrd_utils/str.py, tests/test_utils.py
In `make_file_id`, if the input file's ID does not contain the input fileGrp, then do not attempt to extract the numerical part of the pageId (which might still clash).
But before fallback to purely numerical ID, additionally check if the input file's ID does already contain the pageId: in that case,
only append the output fileGrp to that ID (because it is sufficiently unique already).
(Often file IDs have two numbers, one of which will clash. In that case only the numerical fallback works. On the other hand, often the file IDs from non-OCRD data contain the pageId directly, in which case it's better to stick to that convention.)
=> make_file_id: no page_id number extraction

CHANGELOG.md, ocrd/bashlib/src/dumpjson.bash, ocrd/bashlib/src/parse_argv.bash, ocrd/bashlib/src/wrap.bash, ocrd/ocrd/cli/bashlib.py, ocrd/ocrd/cli/ocrd_tool.py, ocrd/ocrd/lib.bash, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/str.py, ocrd_utils/setup.py, tests/model/test_ocrd_mets.py, tests/test_utils.py
Preparing the next release, includes:
* #758 
*  #744 
* #753
I would also like to include #700 if we can resolve the discussion on short notice, otherwise in the next release in a few weeks.
=> Release 2.29.0

ocrd_utils/ocrd_utils/image.py, tests/utils/test_image.py
This limit is pretty arbitrary but I have not come across any image even close to this large and it would be enough to handle the 2559x37192 image mentioned in https://github.com/tesseract-ocr/tesseract/issues/3184 - though `ocrd-tesserocr-recognize` would still fail currently because the MAX_IMAGE_PIXELS change here only relates to the Python API, not the tesseract API.
=> Allow images with up to 40k by 40k pixels, fix #735

ocrd/ocrd/processor/base.py, ocrd/ocrd/resource_manager.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/os.py
This partially implements #750,. `ocrd-processor --list-resources` will show directories as well as files and will traverse one level down from the processor data location to support subdirectories like in tesseract (`script/Fraktur.traineddata` etc.)
=> Show resource subdir

ocrd/bashlib/src/parse_argv.bash, ocrd/ocrd/lib.bash
This is needed for processors that have _required_ parameters – otherwise the ocrd__wrapped `ocrd validate tasks` will fail.
=> bashlib parse_argv: must validate with params

ocrd/ocrd/resource_list.yml, ocrd/ocrd/resource_manager.py
OCR-D/ocrd_anybaseocr#89
Since #800 still needs tests, for now in the central resource list.
=> change ocrd-anybaseocr-layout-analysis model

ocrd/ocrd/workspace.py, ocrd_utils/ocrd_utils/image.py, tests/test_workspace.py
Attempt to expose [the recropping problem](https://github.com/OCR-D/core/issues/687#issuecomment-1067920406) and then solve it. 
(Currently the test still succeeds, i.e. it does not correctly capture the problem. You can only see the warning `ocrd_utils.crop_image:image.py:468 crop coordinates ((0, 25, 932, 407)) exceed image (932x382)` if you run `python -m pytest -rpP tests/test_workspace.py::test_deskewing`.)
=> Fix recropping

Makefile
=> Remove unneeded dependency python3-pip

ocrd/ocrd/workspace.py
Motivation for this: since we have deprecated `Workspace.resolve_image_as_pil` (because it cannot calculate the coordinate transform that would belong to the image; and we don't want processors to search for AlternativeImages from scratch), we lost a way to deal with the use-case that the caller does _not_ want to create new images dynamically, but instead already knows the desired AlternativeImage (and therefore its path).
Here we therefore (re)introduce that possibility with a kwarg `filename` for the image retrieval functions. (So the difference is that now you have to pass an image path that belongs to an existing AlternativeImage, but then you do get the coordinate transform along with the image.)
@kba I can see no harm here and have already tested locally.
=> Workspace.image_from_*: allow filtering by filename

Makefile
To make this `cp` command work on macOS, the `-t` was removed and 2 arguments were swapped.
=> Fix the cp command so that it also works on macOS.

ocrd/ocrd/resource_manager.py, tests/test_resource_manager.py
This is a "convenience behavior" by the YAML parser, to try to parse strings as datetime. This PR stops this behavior.
=> resmgr: do not parse strings to dates in YAML, fix #867

ocrd/ocrd/cli/log.py
So you can do
```
echo "foo bar
quux" | ocrd log warning -
```
and get
```
13:08:48.815 WARNING root - foo bar
13:08:48.815 WARNING root - quux
```
=> ocrd log: read from stdin if passed "-", fix #852

ocrd_validators/ocrd_validators/bagit-profile.yml, ocrd_validators/ocrd_validators/json_validator.py, ocrd_validators/ocrd_validators/ocrd_tool.schema.yml, ocrd_validators/ocrd_validators/parameter_validator.py, ocrd_validators/ocrd_validators/resource_list_validator.py, tests/validator/test_json_validator.py, tests/validator/test_parameter_validator.py
In particular, needed to upgrade from the draft 4 to draft 6 implementation to support `exclusiveM{in,ax}imum`.
=> New JSON-Schema constructs for ocrd-tool.json validator

ocrd_models/ocrd_models/ocrd_mets.py
Minor bug: change maxsplits to 1, because `generate_range` expects exactly two params.
> If maxsplit is given, at most maxsplit splits are done (thus, the list will have at most maxsplit+1 elements
https://docs.python.org/3/library/stdtypes.html?highlight=split#str.split
=> small bugfix in OcrdMets.find_files

ocrd/ocrd/decorators/__init__.py, ocrd/ocrd/decorators/ocrd_cli_options.py, ocrd/ocrd/processor/helpers.py
Following a [recipe on Stackoverflow](https://stackoverflow.com/a/60474929/14474237), this adds an option to run with [cProfile](https://docs.python.org/3/library/profile.html) on the processor CLI via `--profile`.
Example output for `ocrd-cis-ocropy-segment --profile -I BINSBB -O OCROREGIONSXYMASK-BINSBB -P level-of-operation page -P maxseps 50`:
```
Profiling...
INFO processor.OcropySegment - INPUT FILE 0 / phys00005
INFO processor.OcropySegment - Page "BINSBB_0005" uses 319.000000 DPI
INFO processor.OcropySegment - computing line segmentation for page "BINSBB_0005"
...
Profiling completed
760219 function calls (748005 primitive calls) in 157.335 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000  157.335  157.335 …
```
=> Add processor profiling

ocrd/ocrd/cli/resmgr.py, ocrd_utils/ocrd_utils/os.py, tests/cli/test_resmgr.py
An oversight in #800: `ocrd resmgr download` needs to use `OcrdResourceManager.list_available`, not `OcrdResourceManager.find_resources` because the latter only looks in the database, not inspecting the `--dump-json` output.
=> resmgr download: use list_available for dynamic discovery

CHANGELOG.md, ocrd/ocrd/cli/resmgr.py, ocrd/ocrd/decorators/__init__.py, ocrd/ocrd/decorators/ocrd_cli_options.py, ocrd/ocrd/processor/base.py, ocrd/ocrd/processor/helpers.py, ocrd/ocrd/resource_manager.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/os.py, ocrd_utils/setup.py, tests/cli/test_resmgr.py, tests/test_resource_manager.py
This implements proper support for processor's moduledir:
* Processors have a new CLI option `--dump-module-dir` that prints the `moduledir` of the processor
* When downloading a model
* unless `--location` is explicitly overridden, resmgr will inspect the `resource_location` in a processor's `ocrd-tool.json` and select the first one
* if the location is `module`, will get the directory via `--dump-module-dir`
* For `list-installed`, looks up the directory via `--dump-module-dir` and will look in it as well.
This also removes the `find_resources` method which is mostly redundant with `list-available`
It is a draft because I introduced a bug where downloading a model duplicates all the entries for that executable. Will have to debug this further tomorrow.
=> Resource manager respecting processor's moduledir

ocrd/ocrd/processor/base.py
=> Processor.module: handle namespace pkg case

ocrd/ocrd/cli/resmgr.py
=> resmgr download: module location must not use exe subdir

ocrd_utils/ocrd_utils/constants.py
Another glitch that went under the radar. It must be possible to choose `ocrd resmgr download -l module` (even if `module` may already be the default, but it should at least appear as a CLI option).
=> add RESOURCE_LOCATIONS==module (for resmgr CLI)

ocrd/ocrd/lib.bash
Avoids becoming inconsistent between our help text (which now contains `--dump-module-dir` and `--profile`) and the actual implementation. For the moduledir I chose the directory which contains the tool json (because that's how we already handle resources in `ocrd-page-transform`, the only existing bashlib processor with resources yet).
=> bashlib: implement new CLI options

ocrd/ocrd/resource_manager.py
This prevents adding bogus entries to the user database of resource files for resources that have been found during `list-installed` in the module directory.
(Such an entry would henceforth have you believe there exists an unregistered resource, spamming the `list-available` results and obscuring the fact they are simply located in the module directory.)
=> resmgr: avoid adding fake user db entries for module resources

ocrd/ocrd/cli/workspace.py, ocrd_utils/ocrd_utils/str.py, tests/cli/test_workspace.py, tests/test_utils.py
As raised in #922, if `--file-id` is not provided explicitly, `bulk-add` derived it from the `safe_filename(file_path)` and this had three problems:
* `safe_filename` allowed only a subset of ASCII, now all Unicode letters and digits
* `file_id` was derived from `file_path` even when the "file_path" was actually CSV data. Now it either derives it from `file_path` if it is an actual filepath or from the `srcpath` if not. 
* Derived `file_id` did not follow the convention of starting with the `file_grp`. It does now and also only uses the basename of either `file_path` or `srcpath`
=> bulk-add: Improve deriving file_id from other fields

ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/str.py, tests/model/test_ocrd_mets.py, tests/test_utils.py
Adressing #921:
* regular expression, range and literal values can be combined now, e.g. `ocrd workspace find --page-id "PHYS_0001..PHYS_0010,//PHYS_.*[02468],PHYS_9999"` will search for
* PHYS_0001, PHYS_0002 ... PHYS_0010
* every pageId that starts with `PHYS_` and ends with an even number
* PHYS_9999
* if generating a range:
* use the **last** not the **first** number for the range, because pageIds can have multiple sets of numbers in them. E.g. `PHYS_1234_0001..PHYS_1234_0010` did produce a single match `PHYS_1234_0001`, now it will iterate over the last number part.
* If the latter case happens, i.e. start equals end number, this will raise a ValueError now.
=> OcrdMets.find_files: improve search for pageId

ocrd/ocrd/cli/zip.py, ocrd/ocrd/workspace_bagger.py, tests/validator/test_workspace_bagger.py
Hi,
this PR contains the functionality to recreate bagit-checksums (tagmanifest-sha512.txt, manifest-sha512.txt, Payload-Oxum in bag-info.txt ). This is done with a new command: `ocrd zip update`.
The second thing this PR does is remove the `-I` flag from `ocrd zip bag`, because, as seen in the issue #363 the `-I`-flag is hard to understand and does not work as expected.
=> Update bagit-checksums / fix for #363

ocrd/ocrd/cli/zip.py, ocrd/ocrd/workspace_bagger.py, tests/validator/test_workspace_bagger.py
As discussed in https://github.com/OCR-D/core/pull/951 and https://github.com/OCR-D/core/issues/363 this pull request removes the inplace flag from the workspace-bagger functionality.
=> workspace bagger: remove inplace flag

ocrd/ocrd/resource_manager.py, ocrd/requirements.txt
With this PR, users can `ocrd resmgr download` resources in `application/zip` format as well as tarballs. Non-folder (i.e. file) contents of archives are now handled.
=> resmgr: support zip archives and non-folder archive contents

ocrd/ocrd/resource_manager.py
(otherwise dedup will stick to the existing entries)
=> resmgr: insert from tool instead of append

ocrd/ocrd/processor/helpers.py, ocrd/requirements.txt, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/introspect.py, ocrd_utils/requirements.txt
I have created a separate method to get the desired processor class. Both cached and non-cached types are supported. By default, the non-cached processor is returned to preserve the current state. It's possible to try the cached version by setting the additional flag parameter to True.
=> Processor builder outside the run_processor + cached version

ocrd/ocrd/workspace.py, tests/test_workspace.py
This improves the behaviour of the optional automatic workspace backup facility:
- does not instantiate the Manager each time
- already makes a backup at constructor time (before the first changes)
=> Workspace: also add automatic backup on init

ocrd_models/ocrd_models/ocrd_mets.py
This fixes a hitherto undetected bug where any use of `OcrdMets.find_files` (by instantiating an OcrdFile with the default `loctype=OTHER`) would invariably change the `@LOCTYPE` of the respective files to `OTHER` and their `@OTHERLOCTYPE` to `FILE` (even if they are still URLs).
=> OcrdMets.find_files: don't force @LOCTYPE=OTHER

ocrd/ocrd/processor/base.py
Fixes a glitch following #917 which still breaks with namespace packages (e.g. `ocrd resmgr list-installed`)
=> processor.module: fix namespace pkg case

ocrd/ocrd/resource_manager.py, ocrd/requirements.txt
=> resmgr download: guess type from content

ocrd/ocrd/resource_manager.py, ocrd/requirements.txt
fixes #992 
But the supported URLs are somewhat limited IIUC. For our [example](https://drive.google.com/file/d/1olLQOXvt6nYbvW4pES3T_ABqSlWRq9mY), we have to append `/view`. Besides this `/file/d/.../view` pattern, gdown knows about `/presentation/d/.../edit` and `/uc?id=...` URLs.
Anyway – this seems least painful. Might have to extend when more cases arise.
=> Add resmgr Google Drive downloads

ocrd_utils/ocrd_utils/package_resources.py
=> ocrd_utils: adapt to newer importlib.resources API

Dockerfile
Fixes: f1527a2f605f3ea5 ("upgrade base image to 20.04")
=> Dockerfile: Remove unneeded installation of python3-pip

.circleci/config.yml, .github/workflows/docker-image.yml, .scrutinizer.yml, Dockerfile, Makefile, ocrd_utils/requirements.txt
attempts to fix the [docker-cuda](https://app.circleci.com/pipelines/github/OCR-D/core/1605/workflows/6eeae1ef-a008-4163-9b58-9d8570852a3f/jobs/5705) deploy failure.
=> upgrade pip3

ocrd/ocrd/processor/helpers.py, tests/processor/test_processor.py, tests/test_decorators.py
Follow-up to premature #999: there are more places where we pass an empty `ocrd_tool` around that will never be used.
Reasoning (from [ocrd_tesserocr discussion](https://github.com/OCR-D/ocrd_tesserocr/pull/191#issuecomment-1470706375)):
> > That's despite ocrd==2.47.1. Where does the empty ocrd_tool come from???
> 
> Aha! It turns out that my https://github.com/OCR-D/core/pull/999 was premature: we also pass an unnecessary ocrd_tool in other places:
> 
> - run_processor kwarg: https://github.com/OCR-D/core/blob/cff8ddaefec72451795a5e0b4bdb7efc18223d99/ocrd/ocrd/processor/helpers.py#L38
> - run_processor calling get_processor: https://github.com/OCR-D/core/blob/cff8ddaefec72451795a5e0b4bdb7efc18223d99/ocrd/ocrd/processor/helpers.py#L91
> - get_processor kwarg: …
=> run_processor / get_processor: do not pass (empty) ocrd_tool

Makefile
385c595 (Mike's trick to speed up OpenCV and Numpy builds on older Python) should have been formulated without the `--update` here, as it turns out this unfortunately interferes with [numpy version conflicts between TF and H5py](https://github.com/OCR-D/ocrd_all/pull/356#issuecomment-1473642630).
=> avoid forcing opencv and numpy updates

ocrd/ocrd/processor/helpers.py, tests/processor/test_ocrd_dummy.py
In #972, I missed using the context switch required for the cached processor instances to work correctly. Now I am able to reuse cached instances. According to my observations and testing, for both cached and non-cached, that additional line has no side effects.
=> Fix the processor instance caching

Makefile
=> core-cuda: CUDA 11.3 instead of 11.2

.circleci/config.yml, ocrd/ocrd/decorators/ocrd_cli_options.py, ocrd/ocrd/lib.bash, ocrd/ocrd/processor/helpers.py, ocrd/setup.py, ocrd_modelfactory/setup.py, ocrd_models/setup.py, ocrd_network/ocrd_network/deployer.py, ocrd_network/ocrd_network/deployment_utils.py, ocrd_network/setup.py, ocrd_utils/setup.py, ocrd_validators/setup.py
=> add bashlib processing worker, require Python 3.7

ocrd/ocrd/cli/ocrd_tool.py
Note: I have not found a way to bypass the module-level docstring yet.
This will be ocrd.cli.ocrd_tool, for example for bashlib based ocrd-page-transform:
```
Usage: ocrd-page-transform [OPTIONS]
apply arbitrary XSL transformation file for PAGE-XML
> OCR-D CLI: ocrd-tool.json management
> .. click:: ocrd.cli.ocrd_tool:ocrd_tool_cli     :prog: ocrd ocrd-
> tool     :nested: full
...
```
Still, that's better than before, when it also wrote the `Processor` and `Processor.process` docstring:
```
> Processor base class and helper functions. A processor is a tool
> that implements the uniform OCR-D command-line interface for run-
> time data processing. That is, it executes a single workflow step,
> or a combination of workflow steps, on the workspace (represented by
> local METS). It reads …
```
=> ocrd_tool help: remove default docstrings (used by bashlib's ocrd__usage)

Dockerfile
python3-pip can now be removed, and running pip instead of pip3 is sufficient.
This also avoids the installation of python3-setuptools and python3-wheel (requirements of python3-pip).
=> Dockerfile: Use virtual environment

ocrd_validators/ocrd_validators/page_validator.py
when validating Baseline consistency, require a valid TextLine polygon, too
=> fix bug in PageValidator 

Makefile
The command works with both variants.
-E is also supported on macOS while -P is not.
=> Use grep with extended instead of Perl regexp

ocrd/ocrd/resource_manager.py
This improves on errors caused by wrong URLs or misbehaving servers.
(In my case, a URL which previously worked [now yields HTTP 409](https://github.com/bertsky/ocrd_detectron2/actions/runs/5377364734/jobs/9755736373), but resmgr still attempted to unzip the error page.)
=> resmgr download: raise if http >= 400

Makefile, ocrd/ocrd/resource_manager.py, ocrd/requirements.txt, ocrd_modelfactory/ocrd_modelfactory/__init__.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/os.py, ocrd_utils/requirements.txt, tests/utils/test_os.py
I repeatedly find myself in need of this.
BTW, there still is a problem with our tests. I keep getting [`I/O operation on closed file`](https://github.com/pytest-dev/pytest/issues/14) in test_logging.py when running in local environments. More explanations [here](https://github.com/pytest-dev/pytest/issues/5743). Also explains our previous problems with [click.CliRunner](https://github.com/pytest-dev/pytest/issues/3344) I believe. I don't know how to actually fix this, but running with `-s` helps as a workaround.
Let's see how the CI reacts.
=> allow plain paths in page_from_file

ocrd/ocrd/cli/workspace.py, ocrd_validators/ocrd_validators/workspace_validator.py
This is necessary as some of our processors do not use `set_pcGtsId(file.ID)`, IINM currently:
=> workspace_validator: allow skipping pcgtsid check

README.md, ocrd/ocrd/cli/__init__.py, ocrd/ocrd/resolver.py, tests/test_resolver.py, tests/test_resolver_oai.py
Fixes #973 (retry facility) and also implements a timeout facility, and provides those to any download use-case besides CLI `ocrd workspace find --download` (e.g. processor's typical `Workspace.download_file(input_file)`, or `WorkspaceValidator(... download=True ...)`.
Since there are so many places which could ultimately trigger `Resolver.download_to_directory`, and we don't want to drag along the new kwargs `retries` and `timeout` everywhere, I chose to control them via **environment variables**:
- `OCRD_DOWNLOAD_RETRIES` → number of attempts
- `OCRD_DOWNLOAD_TIMEOUT` → a single float or a comma-separated tuple of floats (connection timeout, read timeout)
The retry facility itself only triggers on certain HTTP statuses (i.e. opt-in), which is debatable (e.g. I have seen proposals opting …
=> download: add retry and timeout kwargs, controlled via env vars

ocrd_network/ocrd_network/cli/processing_worker.py, ocrd_network/ocrd_network/processing_worker.py, ocrd_network/ocrd_network/server_utils.py, ocrd_network/requirements.txt, ocrd_validators/ocrd_validators/processing_server_config.schema.yml
This are mainly only small additions to ocrd_network which I need for the slim containers.
Summary:
- Possibility to create a queue for a worker when the worker is externally managed. Previously only the processing-server was able to create a queue for a worker. 
- Retry for queue creation: When a worker is started at the same time as the rabbit-mq, the rabbitmq needs up to 2 seconds to be fully available so that a queue can be created.
- allow starting a processing-server without any workers or processor-servers
- limit pydantic to version 1. Version 2 was released in June 2023 and conflicts with current models which were created for pydantic v1
=> ocrd network extension

ocrd/ocrd/cli/resmgr.py
This likely fixes a bug where (starting from Python 3.8) confusing the argument `basedir` with a (non-existing) keyword arg `basedir=` (and later in the argument list) caused a wrong CWD-based fpath result (IIUC).
=> cli.resmgr.download: fix basedir

ocrd/ocrd/cli/ocrd_tool.py
changes the implementation of `ocrd ocrd-tool PATH version` to print something like …
```
0.1.2
```
…instead of…
```
Version "0.1.2", ocrd/core "2.45.0"
```
…(which cannot easily be parsed futher, esp. in bashlib, and is therefore not in accordance with non-bashlib processors).
=> ocrd-tool version: print exact tool version

ocrd/ocrd/cli/ocrd_tool.py, ocrd/ocrd/decorators/__init__.py, ocrd/ocrd/decorators/ocrd_cli_options.py, ocrd/ocrd/lib.bash, ocrd/ocrd/processor/base.py, ocrd/ocrd/processor/helpers.py, ocrd_network/ocrd_network/deployer.py
- Instead of an option `--agent-type`, implement the behavior as subcommands, i.e.
```
ocrd-foo --agent-type worker ...
```
becomes
```
ocrd-foo worker ...
```
Also removes the exception handling because it does not actually handle the exceptions, just stringifies them and we want full stack traces if something goes wrong.
=> replace --agent-type with subcommand, #1032, #1085

ocrd/ocrd/lib.bash
When implementing the three `--help` options for bashlib in #1087, I didn't properly test the plain `--help` option, which led to an "unbound variable" error. This PR fixes that.
=> bashlib: fix --help output

ocrd/ocrd/processor/helpers.py
I missed adding the `mets_server_url` kwarg to `run_cli` when finishing #966, now added.
Also remove duplicate lines from the `--help` output.
=> `run_cli` now also supports the METS server

ocrd/ocrd/mets_server.py, tests/test_mets_server.py
PR rectifies the wrong fix in #1098, which changed permissions and started/stopped the socket in the client not the server.
Also ensures that the socket file is removed on shutdown.
=> Mets server fixes 2023 09 15

ocrd/ocrd/cli/log.py, ocrd/ocrd/cli/network.py, ocrd/ocrd/decorators/__init__.py, ocrd/ocrd/mets_server.py, ocrd/ocrd/processor/helpers.py, ocrd_models/ocrd_models/ocrd_exif.py, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_models/ocrd_models/utils.py, ocrd_network/ocrd_network/deployer.py, ocrd_network/ocrd_network/processing_server.py, ocrd_network/ocrd_network/processing_worker.py, ocrd_network/ocrd_network/processor_server.py, ocrd_network/ocrd_network/rabbitmq_utils/constants.py, ocrd_network/ocrd_network/rabbitmq_utils/consumer.py, ocrd_network/ocrd_network/rabbitmq_utils/publisher.py, ocrd_utils/ocrd_logging.conf, ocrd_utils/ocrd_utils/image.py, ocrd_utils/ocrd_utils/logging.py, ocrd_utils/ocrd_utils/os.py, tests/test_resolver_oai.py, tests/test_workspace.py
This is a colophon to #1080
- changing the logger names - all OCR-D/core logging except for `ocrd_network` now are derived from the `ocrd` logger
-  making the logger names in `ocrd_network` explicit
- removing the custom logging code in `ocrd_network` and porting the defaults to the config file and `ocrd_utils.logging` resp.
- simplifying the naming in the logging configuration file and removing now unrequired logger configs 
Unfortunately, there is a heisenbug for (ironically) `test_log_error` in `tests/cli/test_log.py`. Error goes away when replacing the `StreamHandler` of `consoleHandler` with a `FileHandler` in the logging configuration - which isn't even used in that test. I tried `git bisecting` through the changes, but it only appears in the commit 660b46806. If anybody (@m3ssman …
=> Harmonize loggers

ocrd_network/ocrd_network/database.py, ocrd_network/ocrd_network/processing_server.py
This contains a new endpoint to query the status of a workflow run and improved error handling for the workflow-enpoint. This were some of the parts we realized in our last meeting we need improvements in.
=> Additions to the workflow-endpoint

ocrd/ocrd/mets_server.py, tests/test_mets_server.py
Since https://github.com/pydantic/pydantic/pull/6797 a field name starting with underscore (e.g. `_type` in OcrdAgentModel) raise `NameError`. Noticed in https://app.circleci.com/pipelines/github/OCR-D/ocrd_olena/178/workflows/669e922c-b637-4edc-9db7-d3ae5c7a7b1d/jobs/180 . This PR fixes that with as few changes as possible.
=> :bug: pydantic fields must not start with underscore

ocrd/ocrd/cli/__init__.py, ocrd_network/ocrd_network/database.py, ocrd_network/ocrd_network/deployer.py, ocrd_network/ocrd_network/logging.py, ocrd_network/ocrd_network/models/job.py, ocrd_network/ocrd_network/processing_server.py, ocrd_network/ocrd_network/processing_worker.py, ocrd_network/ocrd_network/processor_server.py, ocrd_network/ocrd_network/server_cache.py, ocrd_network/ocrd_network/server_utils.py, ocrd_utils/ocrd_utils/config.py
This PR improves the logging mechanism of the `ocrd_network` module.
Additions:
- A separate logging dir tree structure for the modules (processing servers, processing workers, processor servers, mets servers, processing jobs). Configurable with an env variable.
- Processing job-level logging - each job is logged into a separate file with format `{job_id}.log`
- Processing job-level logging file paths are added to the Job models and preserved in the database.
- The `ocrd_network` logging is based on the format provided in `ocrd_utils`
- Support env variables for setting the root directory for logging/sockets
- An endpoint for getting the log file of a processing job of a processor
Feel free to recommend suggestions.
=> Improve ocrd_network logging

Makefile, ocrd/ocrd/cli/__init__.py, ocrd_utils/ocrd_logging.conf, ocrd_utils/ocrd_utils/config.py, ocrd_utils/ocrd_utils/logging.py, tests/base.py, tests/test_logging_conf.py
- The `ocrd_models` logger was already redundant, removed
- attach fileHandler to both root and `ocrd` logger
- reduce log level of the `ocrd` logger from `ERROR` to `INFO`
Background is that we ship the configuration as `/etc/ocrd_logging.conf` with the docker containers. With the current setup this led to an empty `ocrd.log` being created and debugging further impeded by the high log level.
Maybe we should go even lower and default to logging everything (`DEBUG`). It is always possible to provide a custom logging config to fine-tune the behavior, but the main goal should be to offer as much information as possible for debugging- thoughts?
=> ocrd_logging.conf: attach fileHandlers

ocrd/ocrd/processor/helpers.py
The log-level is provided as an Integer but a String, `'DEBUG' ` for example, is needed.
=> Fix loglevel type error when starting bashlib worker

ocrd/ocrd/lib.bash, ocrd/ocrd/processor/helpers.py, ocrd_network/ocrd_network/process_helpers.py
This PR fixes the logging errors of type:
```
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.7/logging/__init__.py", line 1028, in emit
stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
```
EDIT: Forcing InitLogging() just for Python processors but not for bashlib processors was the simple fix.
=> Fix logging to a file with bashlib based processors

ocrd_network/ocrd_network/processing_server.py, ocrd_network/ocrd_network/processor_server.py, ocrd_network/ocrd_network/server_utils.py
This is to simplify the api for handling processor requests. `processor_name` is removed where it is not needed and the remaining paths are adapted to that.
As discussed on Monday. Separate PR for workflow will follow later.
=> Change api processor paths in ocrd_network

ocrd/ocrd/cli/workspace.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/str.py, tests/cli/test_workspace.py, tests/data/list-page-workspace/mets.xml, tests/test_utils.py
This extends the functionality of `ocrd workspace list-page` with a number of options to support different output formats, partitioning the list of pageIds into roughly equally distributed chunks and supporting both pageId and numerical ranges.
E.g. for a workspace with non-contiguous pageIds `PHYS_0001..PHYS_0006,PHYS_0008..PHYS_0009..PHYS_0021,PHYS_0023..PHYS_0029` (i.e. PHYS_007 and PHYS_0021 missing, cf. test workspace in the PR).
```
ocrd workspace list-page --help
Usage: ocrd workspace list-page [OPTIONS]
List physical page IDs
Options:
-f, --output-format [one-per-line|comma-separated|json]
Output format
-D, --chunk-number INTEGER      Partition the return value into n roughly
equally sized chunks
-C, --chunk-index INTEGER       Output the nth chunk of results, -1 for all
of them. …
```
=> ocrd workspace list-page: implement partioning, #1140

ocrd/ocrd/task_sequence.py, ocrd_network/ocrd_network/database.py, ocrd_network/ocrd_network/deployment_utils.py, ocrd_network/ocrd_network/models/__init__.py, ocrd_network/ocrd_network/models/workflow.py, ocrd_network/ocrd_network/processing_server.py, ocrd_network/ocrd_network/utils.py
Change the two existing workflow paths to run a workflow and to query a workflow job. 
Add endpoints for uploading, updating and downloading a workflow script. The scripts are stored in the mongodb.
Workflows can be run with a previously uploaded script or with providing a script when starting the workflow.
=> Workflow extension

ocrd_utils/ocrd_utils/str.py, tests/test_utils.py
Problematic example case: 25 pages, 8 chunks -> 3,125 pages per chunk, the chunk should contain 3 pages, but contains 4 (due to the ceil method used), which makes the 7th chunk (chunk index 6) having only the 25th page, and the 8th chunk (chunk index 7) being empty which triggers an exception. Using the floor method would introduce other errors such as page overflowing (e.g., 3 pages per chunk is 24 pages, and the 25th page is lost).
Simply using NumPy, prevents such edge cases. 
Old output range: [[1, 2, 3, 4], [5, 6, 7, 8],..., [21, 22, 23, 24], [25]]
New output range: [[1, 2, 3, 4], [5, 6, 7],..., [20, 21, 22], [23, 24, 25]] 
Of course, it is also possible to have chunks divided based on leaps, e.g. [[1](https://stackoverflow.com/a/26021382)]:
```python
def chunks(l, amount):
if amount …
```
=> Fix ocrd workspace list-page: page ranges

ocrd/ocrd/cli/workspace.py
Using `list-page` implies a need to know the list of pages, i.e. `mets:div` in the `PHYSICAL` structMap. So, we should not include `None` in the (generation of the) output list, which led to the issue raised in #1148.
=> ocrd workpace list-page: ignore files without pageId, fix #1148

ocrd/ocrd/cli/bashlib.py, ocrd/ocrd/cli/process.py, ocrd/ocrd/cli/validate.py, ocrd/ocrd/cli/workspace.py, ocrd/ocrd/cli/zip.py, ocrd/ocrd/decorators/ocrd_cli_options.py, ocrd/ocrd/resolver.py, ocrd/ocrd/workspace.py, ocrd/ocrd/workspace_backup.py, ocrd/ocrd/workspace_bagger.py, ocrd_network/ocrd_network/cli/client.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_utils/ocrd_utils/constants.py, ocrd_validators/ocrd_validators/workspace_validator.py
As discussed in https://github.com/slub/mets-mods2tei/pull/68, the `cli.workspace.WorkspaceCtx` class and `Resolver.resolve_mets_arguments` method now have defaults for `mets_basename` and `mets_server_url`.
Also, I replaced all hard-coded `metx.xml` with a constant `DEFAULT_METS_BASENAME` to avoid typos and make it easier to spot where we assume the default basename.
=> defaults for mets_basename and mets_server_url

ocrd_models/ocrd_models/utils.py
Perhaps we should exhaustively search for all such places...
IMHO core logging should not be gabby by default. 
You can of course argue that the user could increase their default logger `ocrd*` filter levels. But that's already an expert step.
In that light, I really don't understand what motivated https://github.com/OCR-D/core/commit/ed33ac69b4fd3c6ffd7033245ab2ff37f6d80b16 (maybe @kba can elaborate) and recommend reverting (i.e. raising the root and `ocrd` loggers, used both on the default console and file handler, to `INFO` again).
=> ocrd_utils.is_oai_content: downgrade loglevel

.circleci/config.yml, Makefile
Since we switched to `pyproject.toml`, we also require `setuptools>61`. And it looks like setuptools, since at least `64` does not support `pip install --editable` the way it used to. In particular, it does not seem to be able to handle the folder structure `ocrd_x/ocrd_x/__init__.py`.
To reproduce:
```
$ pip install 'setuptools>=64'
$ make install-dev
$ python -c 'from ocrd_utils import getLogger'                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                  
File "<string>", line 1, in <module> …
```
=> Fix --editable install for setuptools>=64, pypa/setuptools#3548

src/ocrd/mets_server.py, src/ocrd/workspace.py
Basically, just add `atexit(self.shutdown)`, so the socket file is removed when the process exits. This should cover most of the things that can go wrong, except `kill -9`/`C-\` which cannot be caught.
=> METS Server: try to remove UDS socket at sys.exit

requirements.txt, src/ocrd/processor/helpers.py, src/ocrd_utils/__init__.py, src/ocrd_utils/constants.py, src/ocrd_utils/str.py, tests/test_utils.py
The [sparklines](https://github.com/deeplook/sparklines) library we used to visualize memory consumption as block characters is GPLv3, so I made a little replacement that does the same, mostly.
=> replace sparklines library with a simple replacement

Dockerfile.cuda
We introduced multi-stage build in #1164 but forgot to also implement that in the `Dockerfile.cuda`. This PR rectifies that.
=> Dockerfile.cuda must set stage ocrd_core_base

src/ocrd/processor/base.py, src/ocrd/processor/builtin/dummy_processor.py, src/ocrd/workspace.py, src/ocrd_modelfactory/__init__.py, src/ocrd_models/ocrd_file.py, src/ocrd_models/ocrd_mets.py, src/ocrd_models/ocrd_xml_base.py, tests/cli/test_workspace.py, tests/model/test_ocrd_file.py, tests/processor/test_ocrd_dummy.py, tests/test_mets_server.py, tests/test_resolver.py, tests/test_workspace.py
=> OcrdFile.local_filename returns str, some typing

requirements_test.txt, src/ocrd_models/ocrd_mets.py, src/ocrd_models/ocrd_page_generateds.py, src/ocrd_models/ocrd_xml_base.py, src/ocrd_models/utils.py, tests/model/test_ocrd_mets.py
This adds typing support for lxml, to spot issues like using `_Element.getchildren` which apparently has been deprecated since 2008...
=> use lxml-stubs/types-lxml for typing support of lxml.etree

Makefile
Because of the alias workaround, `make uninstall` is not enough. Hence the additional target.
See also https://github.com/OCR-D/ocrd_all/issues/416
=> expose uninstall-workaround

.circleci/config.yml, .github/workflows/network-testing.yml, .github/workflows/unit-test.yml, README.md, pyproject.toml, requirements_test.txt
Since 27 June 2023, Python 3.8 is the oldest supported version of Python.
=> Remove old code for unsupported Python 3.7

CHANGELOG.md, src/ocrd/processor/base.py, src/ocrd/workspace_bagger.py, src/ocrd_models/ocrd_mets.py, src/ocrd_models/ocrd_page_generateds.py, src/ocrd_network/runtime_data/network_agents.py, src/ocrd_utils/config.py, src/ocrd_utils/logging.py, src/ocrd_utils/os.py, tests/model/test_ocrd_mets.py, tests/model/test_ocrd_page.py, tests/test_logging_conf.py, tests/test_resolver.py, tests/test_workspace.py, tests/utils/test_deprecate.py
Most typos were found by `codespell` and `typos`.
=> Fix some typos and help texts

Makefile
The `make coverage` test does not anticipate that `test-logging` is run in a temporary directory. This PR at least removes `.coverage` so `make coverage` won't fail, but we should find a way to have those results reflected in the total coverage.
=>  make test-logging: remove .coverage if it exists

src/ocrd/decorators/__init__.py, src/ocrd/decorators/ocrd_cli_options.py, src/ocrd/processor/base.py, src/ocrd/workspace.py
fixes #1255 
(and like I proposed there, I cherry-picked a few things from #1240)
=> Fix processor resolve preset

src/ocrd/mets_server.py
The METS Server does not start if its desired socket file already exists. When experimenting with ocrd-network the socket file occasionally is not deleted on mets-server shutdown in some edge-cases e.g. killing the processing-server manually. Workaround is to just delete the socket file manually which is cumbersome.
This change tests if the socket file exists and deletes it in case it is not used by any socket.
=> Remove unused socket file on METS Server startup

tests/network/docker-compose.yml
Increase the retries amount in the health check block of RabbitMQ and MongoDB services to avoid rarely occurring timeouts.
Check https://github.com/OCR-D/core/pull/1239#issuecomment-2194441324
=> fix: increase health check retries

src/ocrd/cli/resmgr.py, src/ocrd/resource_manager.py
~A fix for https://github.com/OCR-D/core/issues/1245 and some minor refactoring related to strings.~
- Some minor refactoring over the resource manager.
- A fix for #1201
- If overwrite is not set, the existing entries will be skipped with a warning instead of raising an exception
=> fix: Resource Manager: Unlink archives after extracting #1245

src/ocrd/resource_manager.py, src/ocrd_utils/os.py
A partial fix for #1218.
There are still some annoying Tensorflow prints. Unfortunately, these cannot be disabled from the core or I am unaware how.
```sh
(venv38-core) mm@MM-Notebook:~/repos/core$ ocrd resmgr list-available
2024-07-04 12:17:53.701854: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-04 12:17:53.778978: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation …
```
=> fix: resmgr list-available * includes non-processors (again) #1218

src/ocrd/resolver.py, tests/test_resolver.py
As laid out in #563, the `clobber_mets` behavior was different from what the docstring said. Instead of raising and Exception if the METS file already existed and `clobber_mets` being `False`, the METS file was silently skipped.
The easiest way would have been to just change the docstring. But the current behavior is problematic because silently skipping downloading/copying the METS XML will lead to hard-to-debug errors when users subsequently work on the wrong METS XML file.
=> Raise FileExistsError in Resolver.workspace_from_url if clobber_mets is False

src/ocrd/cli/workspace.py
fixes #1202 and a regression that printed a removal notice instead of the requested output fields when undoing downloads
=> workspace find: print correct output fields

src/ocrd_models/ocrd_exif.py, tests/model/test_exif.py
Added space after %U in ImageMagick identify format prameter.
We work with pyramid Tiffs in our project. Since several images are combined in one file, identify provides all resolutions and resolution units one after the other. However, there is no space between the first and second image and the resolution unit is therefore read incorrectly. 
```
ret = run(['identify', '-format', r'%[resolution.x] %[resolution.y] %U', img.filename], check=False, stderr=PIPE, stdout=PIPE)
...
tokens = ret.stdout.decode('utf-8').split(' ', 3)
```
`['118.11', '118.11', 'PixelsPerCentimeter118.11', '118.11 PixelsPerCentimeter118.11 118.11 PixelsPerCentimeter118.11 118.11 PixelsPerCentimeter118.11 118.11 PixelsPerCentimeter']`
A simple space after the %U should solve the problem
```
ret = run(['identify', …
```
=> Identify provides the wrong ResolutionUnit for pyramid Tiff Files

Dockerfile.cuda-torch
since we installed core in editable mode!
=> Dockerfile.cuda-torch: do NOT rm /build/core

src/ocrd_network/cli/client.py, src/ocrd_network/client.py, src/ocrd_network/client_utils.py
Make the page-wise feature of the processing server toggleable when running workflows with `ocrd network client workflow run`.
Probably a good idea to merge this with #1277 since it touches the same files.
=> post_ps_workflow_request: pagewise configurable

src/ocrd/mets_server.py, src/ocrd_network/runtime_data/deployer.py
Tackling those errors:
`
17:03:19.064 ERROR ocrd_network.tcp_to_uds_mets_proxy - Uds-Mets-Server gives unexpected error. Response: {'_content': b'"A file with ID==FILE_0015_OCR-D-DEWARP_region0002_region0002_line0011.IMG-DEWARP already exists <OcrdFile fileGrp=OCR-D-DEWARP ID=FILE_0015_OCR-D-DEWARP_region0002_region0002_line0011.IMG-DEWARP, mimetype=image/png, url=---, local_filename=OCR-D-DEWARP/FILE_0015_OCR-D-DEWARP_region0002_region0002_line0011.IMG-DEWARP.png]/>  and neither force nor ignore are set"', '_content_consumed': True, '_next': None, 'status_code': 400, 'headers': {'date': 'Tue, 01 Oct 2024 15:03:18 GMT', 'server': 'uvicorn', 'content-length': '364', 'content-type': 'application/json'}, 'raw': <urllib3.response.HTTPResponse object at 0x7fc5ad35cac0>, 'url': …
=> deployer: Remove any pre-existing socket file before starting the server (again)

src/ocrd/mets_server.py, src/ocrd_network/processing_server.py, src/ocrd_network/server_utils.py
Also, use `os.kill` directly in `OcrdMetsServer.kill_process` (no idea why I did that via `subprocess.run` 🤷)
=> add endpoint DELETE /kill_mets_server_zombies to kill -SIGTERM METS servers with ctime > 60mins ago

src/ocrd/mets_server.py, src/ocrd_network/cli/client.py, src/ocrd_network/client.py, src/ocrd_network/client_utils.py, src/ocrd_network/processing_server.py, src/ocrd_network/runtime_data/deployer.py, src/ocrd_network/server_utils.py, src/ocrd_utils/config.py
Provide flexibility to ocrd network client blocking commands by letting users control the printing of outputs.
=> introduce `-p/--print-status` to ocrd network client blocking commands

src/ocrd/mets_server.py, src/ocrd_network/client.py, src/ocrd_network/client_utils.py, src/ocrd_network/processing_server.py, src/ocrd_network/runtime_data/deployer.py, src/ocrd_network/server_cache.py, src/ocrd_network/server_utils.py, src/ocrd_network/tcp_to_uds_mets_proxy.py, src/ocrd_network/utils.py
This PR fixes:
- No more zombie processes for Mets Servers when they terminate!
- Appropriately deleting the Unix Domain Socket in more complicated configurations (e.g., UDS over TCP multiplexing)
- More extensive logging (to separate files as well) for:
+ `ocrd_network.server_cache.locked_pages`
+ `ocrd_network.server_cache.processing_requests`
+ `ocrd.models.ocrd_mets.server.{self.url}`
+ `ocrd_network.tcp_to_uds_mets_proxy`
Please make sure you adapt your logging configuration file appropriately to avoid extreme amounts of logs. Maybe an adaption is needed to the default logging configuration file - open for discussions.
=> Fix mets server: clean leftover zombie processes

src/ocrd/decorators/__init__.py
Avoids about 17 MB RSS of unnecessary networking imports when _not_ using the networking subcommands on the CLI.
=> CLI decorator: only import ocrd_network when needed

src/ocrd_utils/logging.py, src/ocrd_utils/ocrd_logging.conf, tests/base.py, tests/cli/test_log.py, tests/processor/test_processor.py, tests/test_decorators.py, tests/test_logging.py, tests/test_logging_conf.py, tests/test_mets_server.py
As a follow-up to https://github.com/OCR-D/core/commit/ccb416b13e7f91781568fda8e60ad8182bfea88c, but more general:
`initLogging` should _always_ affect the root logger `''`, too. (Not just when disabling logging.)
Reasons:
- to be consistent with file config (which by default _also_ configures the unqualified `root` logger for our default handlers
- to prevent imported libraries from initializing logging on their own (like `import tensorflow`) – the place to check whether logging has been set up yet is always `getLogger('').hasHandlers()`, also in Python's logging.basicConfig BTW
I know we deliberately changed this to _exclude_ the root logger earlier. But I cannot find the reasoning behind that anymore. Maybe "we are a library, not an application"? Well, I agree actually, but then just …
=> ocrd_utils.initLogging: also add handler to root logger

src/ocrd/decorators/__init__.py
fixes #1223 and replaces #1295
=> ocrd_cli_wrap_processor: always do initLogging

src/ocrd/processor/base.py, src/ocrd/processor/helpers.py, tests/processor/test_processor.py
Needed for proper shutdown of page-parallel processors, esp. in pytest context (think CI).
Sorry to drag this on, but there were still fuzzy deadlocks in 3.0.2 that I did not see earlier.
It appears that is is sufficient to just let go of the QueueListener, without explicitly stopping it.
Tested with ocrd_cis (CLI), ocrd_kraken (Pytest), ocrd_tesserocr (both), ocrd_calamari (Pytest).
=> fixup 39f76258: avoid explicit .stop() for QueueListener

.github/workflows/unit-test.yml, Makefile, src/ocrd/decorators/__init__.py, src/ocrd/processor/base.py, src/ocrd/processor/builtin/dummy/ocrd-tool.json, src/ocrd/processor/helpers.py
Spec actually says this is legitimate. We have processors like ocrd-docstruct, or might have evaluators etc. that simply do not produce output in the form of a file group.
=> Processor: allow empty output file grp

src/ocrd/mets_server.py, src/ocrd/resolver.py, tests/test_mets_server.py
If you try to run a METS Server with relative paths starting with `./`, you would get an `InvalidURL` exception from requests-unixsocket (because dots need to be escaped to `%2E` also), and the client would try to complain about the workspace directory diverging from the server's (because in workspace.cli the `resolver.resolve_mets_arguments` resolved all paths to absolute, but not the METS Server URL). The latter however did not even reach the proper exception, because of the former.
This addresses both. Should really add specific tests for this, too.
=> METS Server: fix problems with "." in path

Makefile, src/ocrd/cli/ocrd_tool.py
Sounds silly, I know, but this will help adding another shortcircuit to all our Dockerfiles:
```Dockerfile
RUN ocrd ocrd-tool ocrd-tool.json dump-module-dirs > $(dirname $(ocrd bashlib filename))/ocrd-all-module-dir.json
```
(circumvents dynamic lookup for `ocrd-some-processor --list-resources` / `ocrd resmgr list-installed` and for `ocrd resmgr download`)
=> ocrd ocrd-tool: add dump-module-dirs command
