OCR-D/core

ocrd/characterize/__init__.py, ocrd/characterize/characterizing.py, ocrd/init/__init__.py, ocrd/init/initializing.py, ocrd/scripts/run.py, requirements.txt
=> * basic infrastructure for image characterization

ocrd/scripts/run_server.py, ocrd/webservices/__init__.py, ocrd/webservices/segment.py, requirements.txt, setup.py
fixes #21  
- very simple web server for page segmentation
- lots of subsequent ToDos
=> * basic webserver

.gitignore, Makefile, docs/api/ocrd.model.rst, docs/api/ocrd.processor.recognize.rst, docs/api/ocrd.processor.rst, docs/api/ocrd.processor.segment_line.rst, docs/api/ocrd.processor.segment_region.rst
`make docs` will build the HTML docs and add them to a checked out version of the `gh-pages` branch. Actual adding&comitting still needs to happen manually.
=> Docs gh pages

ocrd/model/ocrd_mets.py, ocrd/model/ocrd_xml_base.py, ocrd/processor/base.py, ocrd/processor/characterize/exif.py, ocrd/workspace.py, test/model/test_ocrd_mets.py, test/processor/test_exif.py, test/test_resolver.py
A more general method to find files referenced in METS.
=> Mets files_in_group -> find_files

ocrd/model/ocrd_file.py, ocrd/model/ocrd_mets.py, test/model/test_ocrd_mets.py
=> groupId for mets file

.gitignore, Makefile, test/base.py
https://github.com/OCR-D/ocrd-assets/pull/5
=> More uniform asset handling by ocrd-assets itself

ocrd/utils.py
=> resolver_cache: replace non-alnum chars with single dot, fix #84

CHANGELOG.md, ocrd/cli/workspace.py, ocrd/decorators.py, ocrd/model/yaml/ocrd_tool.schema.yml, ocrd/processor/base.py
=> decorator-wrapped MP support -J/--dump-json, fix #109

CHANGELOG.md, ocrd/utils.py, test/test_utils.py
=> utils: mets_file_id -> concat_padded

CHANGELOG.md, ocrd/cli/ocrd_tool.py, ocrd/validator.py
Actually check for `parse-params`.
TODO: required Properties and no additionalProperties check.
=> ocrd ocrd-tool .. tool parse-params does validation now

bashlib/README.md, bashlib/src/parse_argv.bash, bashlib/src/wrap.bash, bashlib/test/args.test.sh, ocrd/lib.bash
explained [here](https://github.com/OCR-D/ocrd_im6convert/issues/2)
=> remove bash 4.4 dependencies

.travis.yml, Dockerfile, Makefile, README.rst, docs/api/ocrd.cli.rst, docs/api/ocrd.rst, requirements_test.txt
Few simplifications and making sure docs are generated for current master.
=> Build setup

ocrd/decorators.py, ocrd/logging.py, ocrd/model/yaml/ocrd_tool.schema.yml, ocrd/utils.py, test/test_cli.py, test/test_logging.py
This should implement the behavior we agreed on in #173.
=> Logging cli

ocrd/logging.py
=> logging: adapt format to specs

ocrd/model/ocrd_exif.py
that was easy (or stupid in the first place)
=> :bug: don't assume pnginfo to be set on exiftool, fix #194

.lgtm.yml, README.rst, ocrd/logging.py
=> LGTM: Ignore generated file

ocrd_models/ocrd_models/ocrd_exif.py
=> 🐛 Handle TIFF ResolutionUnit not being set

ocrd/ocrd/cli/workspace.py, ocrd/ocrd/constants.py
=> Fix bashlib

Makefile, ocrd_models/ocrd_models/constants.py, ocrd_models/ocrd_models/ocrd_page.py, ocrd_models/ocrd_models/ocrd_page_generateds.py, tests/model/test_ocrd_page.py
Switch to 2019-07-15 PAGE-XML namespace, adapting constants and regenerating PAGE API with new features.
=> Adapt to PAGE 2019

Makefile, README.md, docs/conf.py, ocrd/ocrd/constants.py, tests/test_resolver.py
=> replace occurences of 'pyocrd' with 'core'

CHANGELOG.md, ocrd/ocrd/workspace_bagger.py, ocrd_models/ocrd_models/ocrd_file.py, tests/model/test_ocrd_file.py
=> Keep file extension in OCRD-ZIP

ocrd/bashlib/Makefile, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_file.py
=> Fix typos (found by codespell)

ocrd/ocrd/workspace.py
Based on ideas from @wrznr – thanks!!
This is really exciting, it lifts the whole thing to a new level.
The next steps could be:
- writing automated tests for this
- using these features in the processors
- moving from Exceptions to a workflow validation setting by incorporating the feature requirements into the static `ocrd-tool.json`
- modifying OCR-D/spec to reflect and stipulate this solution
=> Feature-based derived image selection/filtering

CHANGELOG.md, ocrd/ocrd/resolver.py, ocrd_validators/ocrd_validators/workspace_validator.py, tests/model/test_ocrd_mets.py, tests/validator/test_workspace_validator.py
First step towards fixing #196, finding a convention that makes both OCR-D repos and PAGE tools happy and cleaning up GT.
=> Validate imagefilename

ocrd/ocrd/workspace_bagger.py
=> add file extension to flocat in METS too

ocrd_models/ocrd_models/ocrd_mets.py
=> fail when adding fileGrp containing commas

ocrd/ocrd/cli/zip.py
pretty sure @bertsky fixed this before but cannot find commit
=> :bug: ocrd zip spill: directory -> dest

CHANGELOG.md, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_exif.py, ocrd_validators/ocrd_validators/workspace_validator.py, tests/validator/test_workspace_validator.py
=> implement check for multi-page TIFF, fix #243

ocrd/ocrd/cli/workspace.py
=> workspace validator: fix CLI param name in 5ca8f73

Dockerfile
c.f. https://github.com/OCR-D/ocrd_tesserocr/pull/97
=> docker: add curl and software-properties-common for apt-add-repository

.lgtm.yml
=> LGTM: Update configuration because of renamed generated file

ocrd/ocrd/processor/base.py
Turns
```
Usage: ocrd-olena-binarize [OPTIONS]
OLENA's binarization algos for OCR-D (on page-level)
Parameters:
"impl" [string - REQUIRED] The name of the actual binarization
algorithm
"win-size" [number] Window size
"k" [number] Sauvola's formulae parameter
Default Wiring:
['OCR-D-SEG-BLOCK', 'OCR-D-SEG-LINE', 'OCR-D-SEG-WORD', 'OCR-D-IMG'] -> ['OCR-D-SEG-BLOCK', 'OCR-D-SEG-LINE', 'OCR-D-SEG-WORD']
Options:
-V, --version                   Show version
-l, --log-level [OFF|ERROR|WARN|INFO|DEBUG|TRACE]
Log level
-J, --dump-json                 Dump tool description as JSON and exit
-p, --parameter TEXT            Parameters, either JSON string or path
JSON file
-g, --page-id TEXT              ID(s) of the pages to process
-O, --output-file-grp TEXT      File group(s) used as output.
-I, …
```
=> reorder --help sections, #402

CHANGELOG.md, ocrd/ocrd/resolver.py, ocrd_utils/ocrd_utils/__init__.py, ocrd_validators/ocrd_validators/workspace_validator.py
=> Fix some typos (found by codespell)

ocrd_models/ocrd_models/ocrd_page.py, ocrd_models/ocrd_models/ocrd_page_generateds.py, requirements_test.txt, tests/model/test_ocrd_page.py
Fixing #269.
Just a first test to make sure runtime dependencies are met.
=> [wip] update generateDS PAGE API

ocrd/bashlib/src/parse_argv.bash, ocrd/ocrd/lib.bash
=> bashlib parse_argv: avoid errexit (catch+raise)

CHANGELOG.md, ocrd_models/ocrd_models/ocrd_page_generateds.py, ocrd_utils/setup.py, tests/model/test_ocrd_page.py
This (temporarily) fixes #451 by (actually) reverting (this time) #437.
=> really revert 3a0a3a8 (generateDS PAGE API)

.gitignore, CHANGELOG.md, Dockerfile, Makefile, ocrd/ocrd/processor/base.py, ocrd_utils/README.md, ocrd_utils/ocrd_logging.conf, ocrd_utils/ocrd_utils/constants.py, ocrd_utils/ocrd_utils/logging.py, requirements_test.txt, tests/base.py, tests/processor/test_processor.py, tests/test_decorators.py, tests/test_logging.py, tests/test_resolver.py, tests/test_workspace.py
=> Execution of processors is tracked with logger "profile.orcd.process.<processor-name>", fix #461

ocrd_utils/ocrd_utils/logging.py, tests/test_logging.py
=> logging: subclass Logger to disable propagation if handler is set

CHANGELOG.md, ocrd/ocrd/cli/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, tests/cli/test_workspace.py, tests/model/test_ocrd_mets.py
=> Mets find multiple page selector

CHANGELOG.md, ocrd/ocrd/cli/dummy_processor.py, ocrd/setup.py, tests/processor/test_ocrd_dummy.py
A minimal processor as proposed in #468
=> Dummy processor

CHANGELOG.md, ocrd/ocrd/cli/workspace.py, tests/base.py, tests/cli/test_workspace.py
fix #495 @M3ssman Can you try please?
=> ocrd workspace add: check file exists with -C/--check-file-exists

CHANGELOG.md, ocrd/ocrd/cli/workspace.py, ocrd/ocrd/workspace.py
=> document regex filtering on CLI

ocrd/bashlib/src/parse_argv.bash, ocrd/bashlib/src/wrap.bash, ocrd/ocrd/lib.bash
Actual implementation in ocrd_olena, ocrd_im6convert still required.
=> bashlib: --overwrite, #476

ocrd/bashlib/src/parse_argv.bash, ocrd/ocrd/cli/ocrd_tool.py, ocrd/ocrd/decorators.py, ocrd/ocrd/lib.bash, ocrd/ocrd/processor/base.py, ocrd_utils/ocrd_utils/__init__.py, tests/processor/test_processor.py, tests/test_decorators.py, tests/test_utils.py
=> Implement -P for parameter overrides

ocrd/bashlib/src/logging.bash, ocrd/ocrd/lib.bash
=> bashlib: avoid activating set -x

ocrd_validators/ocrd_validators/workspace_validator.py
Fixes smaller issues with the workspace validator that I noticed while doing OCR-D/assets#81
=> Workspace validator logspam

ocrd/ocrd/decorators.py, ocrd_utils/ocrd_utils/logging.py
=> setOverrideLoglevel: "silent" argument to omit logging.info call

ocrd/ocrd/task_sequence.py, tests/test_task_sequence.py
So you can do
```sh
ocrd process \
'olena-binarize -P impl sauvola'
```
=> Support -P in ocrd process, fix #551

Makefile
https://github.com/OCR-D/ocrd_tesserocr/pull/138 for context
=> pip install -U pip for make deps-test

ocrd_models/ocrd_models/ocrd_page_generateds.py, ocrd_models/ocrd_page_user_methods/__hash__.py, tests/model/test_ocrd_page.py
fixes https://github.com/OCR-D/ocrd_segment/issues/45
=> ocrd_page: more flexible __hash__

ocrd/ocrd/workspace.py
=> Allow removal of file groups without local file (fix issue #617)

ocrd/ocrd/processor/base.py, ocrd/ocrd/processor/helpers.py
Produces:
```
ocrd-cis-ocropy-deskew -h
Usage: ocrd-cis-ocropy-deskew [OPTIONS]
Deskew regions with ocropy (by annotating orientation angle and adding AlternativeImage)
> Deskew the regions of the workspace.
> Open and deserialise PAGE input files and their respective images,
> then iterate over the element hierarchy down to the TextRegion
> level.
> Next, for each file, crop each region image according to the layout
> annotation (via coordinates into the higher-level image, or from the
> alternative image), and determine the threshold for binarization and
> the deskewing angle of the region (up to ``maxskew``). Annotate the
> angle in the region.
> Add the new image file to the workspace along with the output
> fileGrp, and using a file ID with suffix ``.IMG-DESKEW`` along with
> further …
```
=> processor help: add module/processor/process docstring

ocrd_utils/ocrd_logging.conf, tests/test_logging_conf.py
Attempts to fix https://github.com/OCR-D/core/issues/590 and add testcase
=> [app][fix] fix default logging conf #590

ocrd/ocrd/cli/workspace.py
=> ocrd workspace add: guess mimetype from extension if not provided

ocrd_validators/ocrd_validators/workspace_validator.py
added these while debugging https://github.com/OCR-D/core/issues/324
=> add debug logging to individual validation methods

ocrd/ocrd/processor/base.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_file.py, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/__init__.py
(according to https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html specs)
There's lots more to do in similar fashion, but `workspace` seemed like a good starting point.
=> workspace: fix docstrings

ocrd/ocrd/cli/workspace.py, ocrd/ocrd/decorators/__init__.py, ocrd/ocrd/decorators/mets_find_options.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, tests/model/test_ocrd_mets.py, tests/test_workspace.py
=> Merging METS/workspaces

ocrd/ocrd/processor/base.py, ocrd/ocrd/processor/helpers.py, ocrd/ocrd/resolver.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_file.py, ocrd_models/ocrd_models/ocrd_mets.py
Another round if docstring rST improvements for HTML correct generation (this time only minor changes). I recommend squashing.
=> more API-doc fixes

Makefile, ocrd/ocrd/resource_manager.py, tests/test_resource_manager.py
=> resmgr.add_to_user_database: make sure resdict is always defined

ocrd/ocrd/workspace.py, tests/test_workspace.py
=> workspace.remove-group: handle files not in subdirs gracefully

requirements_test.txt
minor correction of common dependency
=> [app][dep] rather opencv-headless

CHANGELOG.md, ocrd/bashlib/src/dumpjson.bash, ocrd/bashlib/src/parse_argv.bash, ocrd/bashlib/src/wrap.bash, ocrd/ocrd/cli/bashlib.py, ocrd/ocrd/cli/ocrd_tool.py, ocrd/ocrd/lib.bash, ocrd_utils/setup.py
=> bashlib: list-resources, show-resource, and input-files

CHANGELOG.md, ocrd_models/ocrd_models/ocrd_mets.py, tests/model/test_ocrd_mets.py, tests/test_utils.py
=> mets:fileGrp/@USE must be xsd:ID

README.md
Keep information about ImageMagick's delegates and mention also the interference between tests and logging.
=> [doc][upd] note install requirements

ocrd/ocrd/workspace.py
=> workspace.remove_file_group: pass recursive

ocrd/ocrd/workspace.py
Sorry for the changes in format. I'm using Atom Editor on Ubuntu.
=> https://github.com/OCR-D/core/issues/838

ocrd/ocrd/cli/workspace.py
=> workspace bulk_add: fix automatic file_id

ocrd_utils/ocrd_utils/str.py, tests/cli/test_workspace.py
=> safe_filename: allow underscore, avoid dot

CHANGELOG.md, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/str.py, tests/cli/test_workspace.py, tests/model/test_ocrd_mets.py
=> OcrdMets.find_files: allow pageId regex, precompile all regexes

ocrd/ocrd/cli/resmgr.py, ocrd/ocrd/resource_manager.py, tests/test_resource_manager.py
Fix for https://github.com/OCR-D/core/issues/854
=> Resmgr list available nonexisting

ocrd/ocrd/resource_list.yml
Note: I did not include the 2022 version because the code [cannot use it yet](https://github.com/qurator-spk/eynollah/issues/78).
=> resource_list: update eynollah URL

CHANGELOG.md, README.md, ocrd_models/ocrd_models/ocrd_page_generateds.py, ocrd_models/ocrd_page_user_methods/exportChildren_GroupType.py, ocrd_utils/README.md, ocrd_utils/ocrd_logging.conf, ocrd_validators/ocrd_validators/mets.xsd
=> Fix some typos (most of them found by codespell)

ocrd/ocrd/cli/workspace.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, tests/test_workspace.py
=> Improve workspace merge

CHANGELOG.md, ocrd/ocrd/cli/workspace.py, ocrd/ocrd/processor/builtin/dummy_processor.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_validators/ocrd_validators/json_validator.py, ocrd_validators/ocrd_validators/parameter_validator.py, ocrd_validators/ocrd_validators/resource_list_validator.py, tests/cli/test_workspace.py, tests/processor/test_processor.py, tests/test_decorators.py, tests/test_task_sequence.py, tests/test_workspace.py, tests/validator/test_json_validator.py, tests/validator/test_parameter_validator.py
Draft PR for next release to be released on Monday. Includes #874 #872 #888 #880
=> Release 2.36.0

ocrd/ocrd/workspace_bagger.py, tests/validator/test_workspace_bagger.py
currently bagging and spilling with bags not containing mets.xml but a different name for the mets don't work. This pr should fix this and make it possible to create bagits and to convert (spill) workspaces from bagits where the metsfile-name is changed and Ocrd-Mets is set in bag-info.txt
=> workspace_bagger: fixes for bag and spill with bagits having mets-name other than mets.xml

CHANGELOG.md, ocrd/ocrd/cli/resmgr.py, ocrd/ocrd/cli/workspace.py, ocrd/ocrd/cli/zip.py, ocrd/ocrd/decorators/__init__.py, ocrd/ocrd/decorators/ocrd_cli_options.py, ocrd/ocrd/processor/helpers.py, ocrd/ocrd/workspace_bagger.py, ocrd_utils/ocrd_utils/os.py, tests/cli/test_resmgr.py, tests/validator/test_ocrd_zip_validator.py, tests/validator/test_workspace_bagger.py
Obsolete because https://github.com/OCR-D/spec/pull/182
=> Drop manifestation depth

ocrd/ocrd/cli/resmgr.py
=> cli.resmgr download: fix download *

ocrd/ocrd/resource_manager.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py
=> resmgr list-installed: downgrade log msg to debug

CHANGELOG.md, ocrd/ocrd/cli/resmgr.py, ocrd/ocrd/lib.bash, ocrd/ocrd/resource_manager.py, ocrd/ocrd/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, ocrd_utils/ocrd_utils/constants.py, ocrd_utils/setup.py, tests/model/test_ocrd_mets_cache.py
@MehmedGIT These are for #875.
=> Cache functionality kba

ocrd_validators/ocrd_validators/workspace_validator.py, tests/validator/test_workspace_validator.py
=> WorkspaceValidator mets_files: allow files without pageId

ocrd/ocrd/decorators/__init__.py
=> ocrd_cli_wrap_processor: remove fake ocrd_tool param

ocrd/ocrd/resource_list.yml
provided by anybaseocr itself with https://github.com/OCR-D/ocrd_anybaseocr/pull/100
=> resmgr: drop anybaseocr models from resource list

.circleci/config.yml, README.md, ocrd/ocrd/cli/bashlib.py, tests/cli/test_bashlib.py
=> bashlib: make input-files n-ary

.circleci/config.yml, .github/workflows/docker-image.yml, Makefile, README.md, tests/cli/test_bashlib.py, tests/validator/test_workspace_bagger.py
=> docker-image: reuse local ghcr.io image instead of docker.io

ocrd/ocrd/processor/base.py
This is a fix for issue #1103. PR to #1083 since the logging in the master branch still needs rework.
=> Fix issue #1103

ocrd/ocrd/decorators/__init__.py
Related to https://github.com/OCR-D/ocrd_tesserocr/issues/196
=> remove dump_json flag

ocrd/ocrd/lib.bash
=> remove logfile from bashlib

ocrd/ocrd/processor/helpers.py, ocrd_network/ocrd_network/process_helpers.py
This PR implements the file handling envisioned in #1123. Unfortunately, the simple solution there is not working when the bashlib processors are natively deployed by the processing server.
=> add file handler for bashlib

ocrd/ocrd/cli/workspace.py, ocrd_models/ocrd_models/ocrd_mets.py, tests/model/test_ocrd_mets.py
=> implement ocrd workspace update-page

.circleci/config.yml
=> CD: push tag latest to Dockerhub, too

.dockerignore, Dockerfile
The src-layout and pyproject.toml changes broke the docker build, this PR fixes that.
=> fix docker builds

src/ocrd_models/ocrd_mets.py, tests/model/test_ocrd_mets.py
=> OcrdMets.get_physical_pages_for: edge case empty list for_fileIds

src/ocrd_models/ocrd_mets.py
also needed for https://github.com/OCR-D/core/issues/1195 in addition to https://github.com/OCR-D/core/pull/1193
=> OcrdMets.add_file: fix finding existing el_pagediv

.scrutinizer.yml, src/ocrd/cli/bashlib.py
=> bashlib input-files: apply download_file on each input_file

src/ocrd_models/ocrd_file.py
=> OcrdFile: fix removing url

Dockerfile
in preparation to ocrd_all PR, see https://github.com/OCR-D/ocrd_all/issues/416
=> docker: install editable

src/ocrd/cli/workspace.py
=> cli.workspace.find --undo-download: only if .url exists, rm files as well unless --keep-files

src/ocrd_utils/config.py
=> ocrd_utils.config.OCRD_LOGGING_DEBUG: fix True

src/ocrd/cli/ocrd_tool.py, src/ocrd/decorators/__init__.py, src/ocrd/decorators/parameter_option.py, src/ocrd/lib.bash, src/ocrd/processor/__init__.py, src/ocrd/processor/base.py, src/ocrd_utils/str.py, tests/processor/test_processor.py, tests/test_decorators.py
=> parameter decorator: resolve path names as resources

src/ocrd/workspace.py
if there already is a .local_filename which does not exist on the filesystem, then try to download it to the same location (without changing the .local_filename or .url)
So this is a partial fix for #1149 (addressing sub-issue 3).
=> Workspace.download_file: download to same local_filename

src/ocrd/cli/process.py, src/ocrd/cli/workspace.py, src/ocrd/resolver.py, src/ocrd/task_sequence.py, src/ocrd/workspace.py, src/ocrd_utils/config.py, tests/cli/test_process.py, tests/test_mets_server.py, tests/test_resource_manager.py, tests/utils/test_os.py
=> ocrd process via METS server option

src/ocrd/workspace.py
=> fix: FileExistsError in add_file in ocrd/workspace.py #1203

src/ocrd_utils/os.py
=> get_ocrd_tool/moduledir: try loading from ocrd-all-*.json in dist

src/ocrd/processor/base.py
fixes issues with v3 processor CIs (during pytest shutdown)
=> Fix processor executor shutdown

Dockerfile.cuda-torch, Makefile
=> fix deps-tf1 requirements DIRSTACK fix

src/ocrd/cli/workspace.py, src/ocrd/mets_server.py, src/ocrd/workspace.py
~~partial~~ complete fix for #1324
=> mets_server.OcrdFileModel: do not convert None to str

CHANGELOG.md, Makefile, src/ocrd/cli/ocrd_tool.py, src/ocrd/cli/workspace.py, src/ocrd/mets_server.py, src/ocrd/workspace.py, src/ocrd_network/logging_utils.py, src/ocrd_utils/config.py, src/ocrd_utils/logging.py
=> Release 3.4.0
